// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// A2aAgentsService handles the "AI SRE/A2A agents" API resource.
type A2aAgentsService service

// Get A2A agent detail.
//
// Return the full configuration of a single A2A agent by ID.
//
// API: POST /safari/a2a-agent/get (remote-agent-read-get).
func (s *A2aAgentsService) ReadGet(ctx context.Context, req *A2aAgentIDRequest) (*A2aAgentItem, *Response, error) {
	out := new(A2aAgentItem)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List A2A agents.
//
// List registered A2A agents visible to the caller across account and team scopes, with pagination.
//
// API: POST /safari/a2a-agent/list (remote-agent-read-list).
func (s *A2aAgentsService) ReadList(ctx context.Context, req *A2aAgentListRequest) (*A2aAgentListResponse, *Response, error) {
	out := new(A2aAgentListResponse)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create A2A agent.
//
// Register a new A2A remote agent the SRE agent can delegate tasks to.
//
// API: POST /safari/a2a-agent/create (remote-agent-write-create).
func (s *A2aAgentsService) WriteCreate(ctx context.Context, req *A2aAgentCreateRequest) (*A2aAgentCreateResponse, *Response, error) {
	out := new(A2aAgentCreateResponse)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete A2A agent.
//
// Soft-delete an A2A agent registration so it can no longer be used.
//
// API: POST /safari/a2a-agent/delete (remote-agent-write-delete).
func (s *A2aAgentsService) WriteDelete(ctx context.Context, req *A2aAgentIDRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Disable A2A agent.
//
// Deactivate an A2A agent so the SRE agent stops delegating to it.
//
// API: POST /safari/a2a-agent/disable (remote-agent-write-disable).
func (s *A2aAgentsService) WriteDisable(ctx context.Context, req *A2aAgentIDRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/disable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Enable A2A agent.
//
// Activate a disabled A2A agent so the SRE agent can delegate to it.
//
// API: POST /safari/a2a-agent/enable (remote-agent-write-enable).
func (s *A2aAgentsService) WriteEnable(ctx context.Context, req *A2aAgentIDRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/enable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update A2A agent.
//
// Edit an A2A agent's card URL, auth, streaming flag, or owning team.
//
// API: POST /safari/a2a-agent/update (remote-agent-write-update).
func (s *A2aAgentsService) WriteUpdate(ctx context.Context, req *A2aAgentUpdateRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/a2a-agent/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
