// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// AccountService handles the "Platform/Account" API resource.
type AccountService service

// Get account detail.
//
// Return the current account's profile and settings.
//
// API: POST /account/info (account-read-info).
func (s *AccountService) Info(ctx context.Context) (*AccountInfo, *Response, error) {
	out := new(AccountInfo)
	resp, err := s.client.do(ctx, "/account/info", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
