// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// AlertEnrichmentService handles the "On-call/Alert enrichment" API resource.
type AlertEnrichmentService service

// Get enrichment rules.
//
// Return the enrichment rule set configured for a specific integration.
//
// API: POST /enrichment/info (enrichment-read-info).
func (s *AlertEnrichmentService) EnrichmentReadInfo(ctx context.Context, req *EnrichmentInfoRequest) (*EnrichmentItem, *Response, error) {
	out := new(EnrichmentItem)
	resp, err := s.client.do(ctx, "/enrichment/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List enrichment rules.
//
// Return the enrichment rule sets for a list of integration IDs.
//
// API: POST /enrichment/list (enrichment-read-list).
func (s *AlertEnrichmentService) EnrichmentReadList(ctx context.Context, req *EnrichmentListRequest) (*EnrichmentListResponse, *Response, error) {
	out := new(EnrichmentListResponse)
	resp, err := s.client.do(ctx, "/enrichment/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Upsert enrichment rules.
//
// Create or fully replace the enrichment rule set for an integration. The entire `rules` array is replaced atomically.
//
// API: POST /enrichment/upsert (enrichment-write-upsert).
func (s *AlertEnrichmentService) EnrichmentWriteUpsert(ctx context.Context, req *EnrichmentUpsertRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/upsert", req, nil)
}

// Get field detail.
//
// Return the configuration of a single incident custom field by ID.
//
// API: POST /field/info (field-read-info).
func (s *AlertEnrichmentService) FieldReadInfo(ctx context.Context, req *FieldInfoRequest) (*FieldItem, *Response, error) {
	out := new(FieldItem)
	resp, err := s.client.do(ctx, "/field/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List fields.
//
// Return all incident custom fields configured for the account.
//
// API: POST /field/list (field-read-list).
func (s *AlertEnrichmentService) FieldReadList(ctx context.Context, req *FieldListRequest) (*FieldListResponse, *Response, error) {
	out := new(FieldListResponse)
	resp, err := s.client.do(ctx, "/field/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create field.
//
// Create a new incident custom field on the account.
//
// API: POST /field/create (field-write-create).
func (s *AlertEnrichmentService) FieldWriteCreate(ctx context.Context, req *CreateFieldRequest) (*CreateFieldResponse, *Response, error) {
	out := new(CreateFieldResponse)
	resp, err := s.client.do(ctx, "/field/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete field.
//
// Delete an incident custom field and asynchronously strip it from existing incidents.
//
// API: POST /field/delete (field-write-delete).
func (s *AlertEnrichmentService) FieldWriteDelete(ctx context.Context, req *DeleteFieldRequest) (*Response, error) {
	return s.client.do(ctx, "/field/delete", req, nil)
}

// Update field.
//
// Update mutable attributes of an existing incident custom field.
//
// API: POST /field/update (field-write-update).
func (s *AlertEnrichmentService) FieldWriteUpdate(ctx context.Context, req *UpdateFieldRequest) (*Response, error) {
	return s.client.do(ctx, "/field/update", req, nil)
}

// Get mapping API detail.
//
// Return detail of a single mapping API by its ID.
//
// API: POST /enrichment/mapping/api/info (mapping-api-read-info).
func (s *AlertEnrichmentService) MappingAPIReadInfo(ctx context.Context, req *MappingApiidRequest) (*MappingAPIItem, *Response, error) {
	out := new(MappingAPIItem)
	resp, err := s.client.do(ctx, "/enrichment/mapping/api/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List mapping APIs.
//
// Return all mapping APIs configured for the account.
//
// API: POST /enrichment/mapping/api/list (mapping-api-read-list).
func (s *AlertEnrichmentService) MappingAPIReadList(ctx context.Context) (*MappingAPIListResponse, *Response, error) {
	out := new(MappingAPIListResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/api/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create mapping API.
//
// Create a new external HTTP API endpoint used to enrich alerts via HTTP lookup.
//
// API: POST /enrichment/mapping/api/create (mapping-api-write-create).
func (s *AlertEnrichmentService) MappingAPIWriteCreate(ctx context.Context, req *MappingAPICreateRequest) (*MappingAPICreateResponse, *Response, error) {
	out := new(MappingAPICreateResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/api/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete mapping API.
//
// Delete a mapping API. Deletion is blocked if the API is referenced by any enrichment rule.
//
// API: POST /enrichment/mapping/api/delete (mapping-api-write-delete).
func (s *AlertEnrichmentService) MappingAPIWriteDelete(ctx context.Context, req *MappingApiidRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/api/delete", req, nil)
}

// Update mapping API.
//
// Update configuration of an existing mapping API.
//
// API: POST /enrichment/mapping/api/update (mapping-api-write-update).
func (s *AlertEnrichmentService) MappingAPIWriteUpdate(ctx context.Context, req *MappingAPIUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/api/update", req, nil)
}

// Download mapping data as CSV.
//
// Export all data rows of a mapping schema as a CSV file download.
//
// The success body is a file, not a JSON envelope: it is returned on Response.Raw.
//
// API: POST /enrichment/mapping/data/download (mapping-data-read-download).
func (s *AlertEnrichmentService) MappingDataReadDownload(ctx context.Context, req *MappingSchemaIDRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/data/download", req, nil)
}

// List mapping data.
//
// Return paginated mapping data rows for a schema, with optional exact-match filtering on source label values.
//
// API: POST /enrichment/mapping/data/list (mapping-data-read-list).
func (s *AlertEnrichmentService) MappingDataReadList(ctx context.Context, req *MappingDataListRequest) (*MappingDataListResponse, *Response, error) {
	out := new(MappingDataListResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/data/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete mapping data rows.
//
// Delete up to 100 mapping data rows by their keys.
//
// API: POST /enrichment/mapping/data/delete (mapping-data-write-delete).
func (s *AlertEnrichmentService) MappingDataWriteDelete(ctx context.Context, req *MappingDataDeleteRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/data/delete", req, nil)
}

// Truncate mapping data.
//
// Delete all data rows in a mapping schema.
//
// API: POST /enrichment/mapping/data/truncate (mapping-data-write-truncate).
func (s *AlertEnrichmentService) MappingDataWriteTruncate(ctx context.Context, req *MappingSchemaIDRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/data/truncate", req, nil)
}

// Upsert mapping data rows.
//
// Insert or update up to 1000 data rows in a mapping schema. Each row must contain all source and result labels.
//
// API: POST /enrichment/mapping/data/upsert (mapping-data-write-upsert).
func (s *AlertEnrichmentService) MappingDataWriteUpsert(ctx context.Context, req *MappingDataUpsertRequest) (*MappingDataUpsertResponse, *Response, error) {
	out := new(MappingDataUpsertResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/data/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get mapping schema detail.
//
// Return detail of a single mapping schema by its ID.
//
// API: POST /enrichment/mapping/schema/info (mapping-schema-read-info).
func (s *AlertEnrichmentService) MappingSchemaReadInfo(ctx context.Context, req *MappingSchemaIDRequest) (*MappingSchemaItem, *Response, error) {
	out := new(MappingSchemaItem)
	resp, err := s.client.do(ctx, "/enrichment/mapping/schema/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List mapping schemas.
//
// Return all mapping schemas for the account, sorted by creation time ascending.
//
// API: POST /enrichment/mapping/schema/list (mapping-schema-read-list).
func (s *AlertEnrichmentService) MappingSchemaReadList(ctx context.Context) (*MappingSchemaListResponse, *Response, error) {
	out := new(MappingSchemaListResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/schema/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create mapping schema.
//
// Create a new mapping schema defining source lookup labels and the result labels to populate. Requires a Pro plan.
//
// API: POST /enrichment/mapping/schema/create (mapping-schema-write-create).
func (s *AlertEnrichmentService) MappingSchemaWriteCreate(ctx context.Context, req *MappingSchemaCreateRequest) (*MappingSchemaCreateResponse, *Response, error) {
	out := new(MappingSchemaCreateResponse)
	resp, err := s.client.do(ctx, "/enrichment/mapping/schema/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete mapping schema.
//
// Delete a mapping schema and all its associated data. Deletion is blocked if the schema is referenced by any enrichment rule or webhook.
//
// API: POST /enrichment/mapping/schema/delete (mapping-schema-write-delete).
func (s *AlertEnrichmentService) MappingSchemaWriteDelete(ctx context.Context, req *MappingSchemaIDRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/schema/delete", req, nil)
}

// Update mapping schema.
//
// Update the name, description, or owning team of a mapping schema. Source and result labels cannot be changed after creation.
//
// API: POST /enrichment/mapping/schema/update (mapping-schema-write-update).
func (s *AlertEnrichmentService) MappingSchemaWriteUpdate(ctx context.Context, req *MappingSchemaUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/enrichment/mapping/schema/update", req, nil)
}
