// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// AlertsService handles the "On-call/Alerts" API resource.
type AlertsService service

// List raw alert events.
//
// Return a cursor-paginated list of raw alert events across all alerts, with filtering by integration, channel, time range, and severity.
//
// API: POST /alert-event/list (alert-event-read-list).
func (s *AlertsService) EventReadList(ctx context.Context, req *AlertEventGlobalListRequest) (*AlertEventGlobalListResponse, *Response, error) {
	out := new(AlertEventGlobalListResponse)
	resp, err := s.client.do(ctx, "/alert-event/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List events for an alert.
//
// Return all raw events that have been ingested into a specific alert, in chronological order.
//
// API: POST /alert/event/list (alert-read-event-list).
func (s *AlertsService) ReadEventList(ctx context.Context, req *AlertEventListRequest) (*AlertEventListResponse, *Response, error) {
	out := new(AlertEventListResponse)
	resp, err := s.client.do(ctx, "/alert/event/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List alert activity feed.
//
// Return the activity feed (comments, state changes, merges, silence events) for a single alert, with page-based pagination.
//
// API: POST /alert/feed (alert-read-feed).
func (s *AlertsService) ReadFeed(ctx context.Context, req *AlertFeedRequest) (*AlertFeedResponse, *Response, error) {
	out := new(AlertFeedResponse)
	resp, err := s.client.do(ctx, "/alert/feed", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get alert detail.
//
// Return the full details of a single alert by its ID, including its associated incident and event count.
//
// API: POST /alert/info (alert-read-info).
func (s *AlertsService) ReadInfo(ctx context.Context, req *AlertInfoRequest) (*AlertItem, *Response, error) {
	out := new(AlertItem)
	resp, err := s.client.do(ctx, "/alert/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List alerts.
//
// Return a cursor-paginated list of alerts matching the given filters.
//
// API: POST /alert/list (alert-read-list).
func (s *AlertsService) ReadList(ctx context.Context, req *AlertListRequest) (*AlertListResponse, *Response, error) {
	out := new(AlertListResponse)
	resp, err := s.client.do(ctx, "/alert/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List alerts by IDs.
//
// Return the details of multiple alerts by their IDs in a single request.
//
// API: POST /alert/list-by-ids (alert-read-list-by-ids).
func (s *AlertsService) ReadListByIDs(ctx context.Context, req *AlertListByIDsRequest) (*AlertListResponse, *Response, error) {
	out := new(AlertListResponse)
	resp, err := s.client.do(ctx, "/alert/list-by-ids", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get alert pipeline.
//
// Return the alert processing pipeline configured for a specific integration.
//
// API: POST /alert/pipeline/info (alert-read-pipeline-info).
func (s *AlertsService) ReadPipelineInfo(ctx context.Context, req *AlertPipelineInfoRequest) (*AlertPipelineItem, *Response, error) {
	out := new(AlertPipelineItem)
	resp, err := s.client.do(ctx, "/alert/pipeline/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List alert pipelines.
//
// Return the alert processing pipelines configured for multiple integrations.
//
// API: POST /alert/pipeline/list (alert-read-pipeline-list).
func (s *AlertsService) ReadPipelineList(ctx context.Context, req *AlertPipelineListRequest) (*AlertPipelineListResponse, *Response, error) {
	out := new(AlertPipelineListResponse)
	resp, err := s.client.do(ctx, "/alert/pipeline/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Merge alerts into an incident.
//
// Associate one or more alerts with an existing incident. If a source alert previously belonged to a different incident and that incident becomes empty after the merge, it will be automatically closed.
//
// API: POST /alert/merge (alert-write-merge).
func (s *AlertsService) WriteMerge(ctx context.Context, req *AlertMergeRequest) (*Response, error) {
	return s.client.do(ctx, "/alert/merge", req, nil)
}

// Create or update alert pipeline.
//
// Set the alert processing pipeline for an integration. Replaces the existing configuration entirely.
//
// API: POST /alert/pipeline/upsert (alert-write-pipeline-upsert).
func (s *AlertsService) WritePipelineUpsert(ctx context.Context, req *AlertPipelineUpsertRequest) (*Response, error) {
	return s.client.do(ctx, "/alert/pipeline/upsert", req, nil)
}
