// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// AnalyticsService handles the "On-call/Analytics" API resource.
type AnalyticsService service

// Get account-level insight.
//
// Return aggregated incident insight metrics for the entire account.
//
// API: POST /insight/account (insightByAccount).
func (s *AnalyticsService) ByAccount(ctx context.Context, req *InsightQueryRequest) (*DimensionInsightResponse, *Response, error) {
	out := new(DimensionInsightResponse)
	resp, err := s.client.do(ctx, "/insight/account", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get channel insight.
//
// Return insight metrics aggregated by channel.
//
// API: POST /insight/channel (insightByChannel).
func (s *AnalyticsService) ByChannel(ctx context.Context, req *InsightQueryRequest) (*DimensionInsightResponse, *Response, error) {
	out := new(DimensionInsightResponse)
	resp, err := s.client.do(ctx, "/insight/channel", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get responder insight.
//
// Return insight metrics aggregated by responder.
//
// API: POST /insight/responder (insightByResponder).
func (s *AnalyticsService) ByResponder(ctx context.Context, req *InsightQueryRequest) (*ResponderInsightResponse, *Response, error) {
	out := new(ResponderInsightResponse)
	resp, err := s.client.do(ctx, "/insight/responder", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get team insight.
//
// Return insight metrics aggregated by team.
//
// API: POST /insight/team (insightByTeam).
func (s *AnalyticsService) ByTeam(ctx context.Context, req *InsightQueryRequest) (*DimensionInsightResponse, *Response, error) {
	out := new(DimensionInsightResponse)
	resp, err := s.client.do(ctx, "/insight/team", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List insight incidents.
//
// Return a paged list of incidents with per-incident handling metrics used by the analytics dashboard.
//
// API: POST /insight/incident/list (insightIncidentList).
func (s *AnalyticsService) IncidentList(ctx context.Context, req *InsightIncidentListRequest) (*InsightIncidentListResponse, *Response, error) {
	out := new(InsightIncidentListResponse)
	resp, err := s.client.do(ctx, "/insight/incident/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get top-K alerts grouped by check or resource.
//
// Return the top-K alert groups aggregated either by `check` or by `resource` label over the specified time range.
//
// API: POST /insight/alert/topk-by-label (insightTopkAlertsByLabel).
func (s *AnalyticsService) TopkAlertsByLabel(ctx context.Context, req *InsightTopkAlertByLabelRequest) (*InsightAlertByLabelResponse, *Response, error) {
	out := new(InsightAlertByLabelResponse)
	resp, err := s.client.do(ctx, "/insight/alert/topk-by-label", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
