// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ApplicationsService handles the "RUM/Applications" API resource.
type ApplicationsService service

// Get application detail.
//
// Retrieve full details of a single RUM application by `application_id`.
//
// API: POST /rum/application/info (rum-application-read-info).
func (s *ApplicationsService) ReadInfo(ctx context.Context, req *RUMApplicationIDRequest) (*RUMApplicationItem, *Response, error) {
	out := new(RUMApplicationItem)
	resp, err := s.client.do(ctx, "/rum/application/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Batch get applications.
//
// Retrieve details for multiple RUM applications by their IDs in one request.
//
// API: POST /rum/application/infos (rum-application-read-infos).
func (s *ApplicationsService) ReadInfos(ctx context.Context, req *RUMApplicationInfosRequest) (*RUMApplicationInfosResponse, *Response, error) {
	out := new(RUMApplicationInfosResponse)
	resp, err := s.client.do(ctx, "/rum/application/infos", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List applications.
//
// Return a paginated list of RUM applications accessible to the current user.
//
// API: POST /rum/application/list (rum-application-read-list).
func (s *ApplicationsService) ReadList(ctx context.Context, req *RUMApplicationListRequest) (*RUMApplicationListResponse, *Response, error) {
	out := new(RUMApplicationListResponse)
	resp, err := s.client.do(ctx, "/rum/application/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Test application webhook.
//
// Send a sample RUM alert event to verify an application's webhook URL.
//
// API: POST /rum/application/webhook/test (rum-application-webhook-test).
func (s *ApplicationsService) WebhookTest(ctx context.Context, req *RUMWebhookTestRequest) (*RUMWebhookTestResponse, *Response, error) {
	out := new(RUMWebhookTestResponse)
	resp, err := s.client.do(ctx, "/rum/application/webhook/test", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create application.
//
// Create a new RUM application. Returns the generated `application_id` and `client_token`.
//
// API: POST /rum/application/create (rum-application-write-create).
func (s *ApplicationsService) WriteCreate(ctx context.Context, req *RUMApplicationCreateRequest) (*RUMApplicationCreateResponse, *Response, error) {
	out := new(RUMApplicationCreateResponse)
	resp, err := s.client.do(ctx, "/rum/application/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete application.
//
// Delete a RUM application by `application_id`.
//
// API: POST /rum/application/delete (rum-application-write-delete).
func (s *ApplicationsService) WriteDelete(ctx context.Context, req *RUMApplicationIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/application/delete", req, nil)
}

// Update application.
//
// Update an existing RUM application. All fields except `application_id` are optional — only provided fields are updated.
//
// API: POST /rum/application/update (rum-application-write-update).
func (s *ApplicationsService) WriteUpdate(ctx context.Context, req *RUMApplicationUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/application/update", req, nil)
}
