// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ApplicationsService handles the "RUM/Applications" API resource.
type ApplicationsService service

// Get application detail.
//
// Retrieve full details of a single RUM application by `application_id`.
//
// API: POST /rum/application/info (rum-application-read-info).
func (s *ApplicationsService) ReadInfo(ctx context.Context, req *RUMApplicationIDRequest) (*RUMApplicationItem, *Response, error) {
	out := new(RUMApplicationItem)
	resp, err := s.client.do(ctx, "/rum/application/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Batch get applications.
//
// Retrieve details for multiple RUM applications by their IDs in one request.
//
// API: POST /rum/application/infos (rum-application-read-infos).
func (s *ApplicationsService) ReadInfos(ctx context.Context, req *RUMApplicationInfosRequest) (*RUMApplicationInfosResponse, *Response, error) {
	out := new(RUMApplicationInfosResponse)
	resp, err := s.client.do(ctx, "/rum/application/infos", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List applications.
//
// Return a paginated list of RUM applications accessible to the current user.
//
// API: POST /rum/application/list (rum-application-read-list).
func (s *ApplicationsService) ReadList(ctx context.Context, req *RUMApplicationListRequest) (*RUMApplicationListResponse, *Response, error) {
	out := new(RUMApplicationListResponse)
	resp, err := s.client.do(ctx, "/rum/application/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get remote config detail.
//
// Retrieve the live remote configuration of a RUM application and the version it is stored under.
//
// API: POST /rum/application/remote-config/get (rum-application-remote-config-read-get).
func (s *ApplicationsService) RemoteConfigReadGet(ctx context.Context, req *GetRemoteConfigRequest) (*GetRemoteConfigResponse, *Response, error) {
	out := new(GetRemoteConfigResponse)
	resp, err := s.client.do(ctx, "/rum/application/remote-config/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List remote config history.
//
// List published remote configuration versions of a RUM application.
//
// API: POST /rum/application/remote-config/history/list (rum-application-remote-config-read-history-list).
func (s *ApplicationsService) RemoteConfigReadHistoryList(ctx context.Context, req *ListRemoteConfigHistoryRequest) (*ListRemoteConfigHistoryResponse, *Response, error) {
	out := new(ListRemoteConfigHistoryResponse)
	resp, err := s.client.do(ctx, "/rum/application/remote-config/history/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Preview remote config.
//
// Evaluate a draft remote configuration against a client context without publishing it.
//
// API: POST /rum/application/remote-config/preview (rum-application-remote-config-read-preview).
func (s *ApplicationsService) RemoteConfigReadPreview(ctx context.Context, req *PreviewRemoteConfigRequest) (*PreviewRemoteConfigResponse, *Response, error) {
	out := new(PreviewRemoteConfigResponse)
	resp, err := s.client.do(ctx, "/rum/application/remote-config/preview", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Revert remote config.
//
// Republish an earlier remote configuration version's content as a new version.
//
// API: POST /rum/application/remote-config/history/revert (rum-application-remote-config-write-history-revert).
func (s *ApplicationsService) RemoteConfigWriteHistoryRevert(ctx context.Context, req *RevertRemoteConfigRequest) (*RevertRemoteConfigResponse, *Response, error) {
	out := new(RevertRemoteConfigResponse)
	resp, err := s.client.do(ctx, "/rum/application/remote-config/history/revert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update remote config.
//
// Publish a complete new remote configuration version for a RUM application.
//
// API: POST /rum/application/remote-config/update (rum-application-remote-config-write-update).
func (s *ApplicationsService) RemoteConfigWriteUpdate(ctx context.Context, req *UpdateRemoteConfigRequest) (*UpdateRemoteConfigResponse, *Response, error) {
	out := new(UpdateRemoteConfigResponse)
	resp, err := s.client.do(ctx, "/rum/application/remote-config/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Test application webhook.
//
// Send a sample RUM alert event to verify an application's webhook URL.
//
// API: POST /rum/application/webhook/test (rum-application-webhook-test).
func (s *ApplicationsService) WebhookTest(ctx context.Context, req *RUMWebhookTestRequest) (*RUMWebhookTestResponse, *Response, error) {
	out := new(RUMWebhookTestResponse)
	resp, err := s.client.do(ctx, "/rum/application/webhook/test", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create application.
//
// Create a new RUM application. Returns the generated `application_id` and `client_token`.
//
// API: POST /rum/application/create (rum-application-write-create).
func (s *ApplicationsService) WriteCreate(ctx context.Context, req *RUMApplicationCreateRequest) (*RUMApplicationCreateResponse, *Response, error) {
	out := new(RUMApplicationCreateResponse)
	resp, err := s.client.do(ctx, "/rum/application/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete application.
//
// Delete a RUM application by `application_id`.
//
// API: POST /rum/application/delete (rum-application-write-delete).
func (s *ApplicationsService) WriteDelete(ctx context.Context, req *RUMApplicationIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/application/delete", req, nil)
}

// Update application.
//
// Update an existing RUM application. All fields except `application_id` are optional — only provided fields are updated.
//
// API: POST /rum/application/update (rum-application-write-update).
func (s *ApplicationsService) WriteUpdate(ctx context.Context, req *RUMApplicationUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/application/update", req, nil)
}
