// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ArtifactsService handles the "AI SRE/Artifacts" API resource.
type ArtifactsService service

// Get artifact detail.
//
// Get a single published artifact by ID.
//
// API: POST /safari/artifact/gallery/get (artifact-read-get).
func (s *ArtifactsService) ReadGet(ctx context.Context, req *ArtifactIDRequest) (*PublishedArtifactItem, *Response, error) {
	out := new(PublishedArtifactItem)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get file publish state.
//
// Check which presented files already have a live published artifact.
//
// API: POST /safari/artifact/gallery/file-state (artifact-read-get-file-state).
func (s *ArtifactsService) ReadGetFileState(ctx context.Context, req *ArtifactFileStateRequest) (*ArtifactFileStateResponse, *Response, error) {
	out := new(ArtifactFileStateResponse)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/file-state", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List artifacts.
//
// List published artifacts visible to the caller, with pagination and title search.
//
// API: POST /safari/artifact/gallery/list (artifact-read-list).
func (s *ArtifactsService) ReadList(ctx context.Context, req *ArtifactListRequest) (*ArtifactListResponse, *Response, error) {
	out := new(ArtifactListResponse)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create signed file URLs.
//
// Create short-lived signed URLs to download or preview a presented file.
//
// API: POST /safari/artifact/sign (artifact-read-sign).
func (s *ArtifactsService) ReadSign(ctx context.Context, req *ArtifactSignRequest) (*SignedUrLs, *Response, error) {
	out := new(SignedUrLs)
	resp, err := s.client.do(ctx, "/safari/artifact/sign", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Download or preview a file.
//
// Download or preview a file's bytes using a signed token.
//
// The success body is a file, not a JSON envelope: it is returned on Response.Raw.
//
// API: GET /safari/artifact/stream (artifact-read-stream).
func (s *ArtifactsService) ReadStream(ctx context.Context, req *ArtifactsReadStreamRequest) (*Response, error) {
	return s.client.doGet(ctx, "/safari/artifact/stream", req, nil)
}

// Remove artifact from gallery.
//
// Detach an artifact from the gallery; the source file stays with its session.
//
// API: POST /safari/artifact/gallery/delete (artifact-write-delete).
func (s *ArtifactsService) WriteDelete(ctx context.Context, req *ArtifactIDRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Publish file as artifact.
//
// Publish a session-produced file to the artifact gallery.
//
// API: POST /safari/artifact/gallery/publish-from-file (artifact-write-publish).
func (s *ArtifactsService) WritePublish(ctx context.Context, req *ArtifactPublishFromFileRequest) (*ArtifactPublishResponse, *Response, error) {
	out := new(ArtifactPublishResponse)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/publish-from-file", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Enable public sharing.
//
// Turn on anonymous public sharing for an artifact and return its public link.
//
// API: POST /safari/artifact/gallery/share/enable (artifact-write-share-enable).
func (s *ArtifactsService) WriteShareEnable(ctx context.Context, req *ArtifactIDRequest) (*ArtifactShareState, *Response, error) {
	out := new(ArtifactShareState)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/share/enable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Revoke public sharing.
//
// Turn off public sharing; the link stops resolving immediately.
//
// API: POST /safari/artifact/gallery/share/revoke (artifact-write-share-revoke).
func (s *ArtifactsService) WriteShareRevoke(ctx context.Context, req *ArtifactIDRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/share/revoke", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update shared snapshot.
//
// Refresh the public snapshot of a shared artifact with its latest content.
//
// API: POST /safari/artifact/gallery/share/sync (artifact-write-share-sync).
func (s *ArtifactsService) WriteShareSync(ctx context.Context, req *ArtifactIDRequest) (*ArtifactShareState, *Response, error) {
	out := new(ArtifactShareState)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/share/sync", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update artifact.
//
// Rename an artifact or transfer it between personal and team scope.
//
// API: POST /safari/artifact/gallery/update (artifact-write-update).
func (s *ArtifactsService) WriteUpdate(ctx context.Context, req *ArtifactUpdateRequest) (*PublishedArtifactItem, *Response, error) {
	out := new(PublishedArtifactItem)
	resp, err := s.client.do(ctx, "/safari/artifact/gallery/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
