// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// AuditLogsService handles the "Platform/Audit logs" API resource.
type AuditLogsService service

// List auditable operation types.
//
// Return all operation names that are recorded in the audit log, for use as `operations` filter values.
//
// API: POST /audit/operation/list (audit-read-operation-list).
func (s *AuditLogsService) OperationList(ctx context.Context) (*AuditOperationListResponse, *Response, error) {
	out := new(AuditOperationListResponse)
	resp, err := s.client.do(ctx, "/audit/operation/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Search audit logs.
//
// Return a cursor-paginated list of audit log entries within a time range.
//
// API: POST /audit/search (audit-read-search).
func (s *AuditLogsService) Search(ctx context.Context, req *AuditSearchRequest) (*AuditSearchResponse, *Response, error) {
	out := new(AuditSearchResponse)
	resp, err := s.client.do(ctx, "/audit/search", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
