// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// CalendarsService handles the "On-call/Calendars" API resource.
type CalendarsService service

// Delete calendar event.
//
// Delete a calendar event by calendar ID and event ID.
//
// API: POST /calendar/event/delete (calEventDelete).
func (s *CalendarsService) CalEventDelete(ctx context.Context, req *CalEventIDRequest) (*Response, error) {
	return s.client.do(ctx, "/calendar/event/delete", req, nil)
}

// List calendar events.
//
// Return events for a personal calendar within a year/month/day scope. When month and day are both omitted the whole year is returned.
//
// API: POST /calendar/event/list (calEventList).
func (s *CalendarsService) CalEventList(ctx context.Context, req *CalEventListRequest) (*CalEventListResponse, *Response, error) {
	out := new(CalEventListResponse)
	resp, err := s.client.do(ctx, "/calendar/event/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Upsert calendar event.
//
// Create or update a calendar event (holiday or workday override). Omit event_id to create a new event.
//
// API: POST /calendar/event/upsert (calEventUpsert).
func (s *CalendarsService) CalEventUpsert(ctx context.Context, req *CalEventUpsertRequest) (*CalEventUpsertResponse, *Response, error) {
	out := new(CalEventUpsertResponse)
	resp, err := s.client.do(ctx, "/calendar/event/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create calendar.
//
// Create a personal service calendar. Each account is limited to 5 calendars unless the Flashcat-Break-Cal-Limit header is set.
//
// API: POST /calendar/create (calendarCreate).
func (s *CalendarsService) CalendarCreate(ctx context.Context, req *CalendarCreateRequest) (*CalendarCreateResponse, *Response, error) {
	out := new(CalendarCreateResponse)
	resp, err := s.client.do(ctx, "/calendar/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete calendar.
//
// Delete a personal service calendar. The call fails when referenced by escalation or silence rules.
//
// API: POST /calendar/delete (calendarDelete).
func (s *CalendarsService) CalendarDelete(ctx context.Context, req *CalendarIDRequest) (*Response, error) {
	return s.client.do(ctx, "/calendar/delete", req, nil)
}

// Get calendar info.
//
// Return details of a service calendar.
//
// API: POST /calendar/info (calendarInfo).
func (s *CalendarsService) CalendarInfo(ctx context.Context, req *CalendarIDRequest) (*CalendarItem, *Response, error) {
	out := new(CalendarItem)
	resp, err := s.client.do(ctx, "/calendar/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List calendars.
//
// Return the list of service calendars visible to the current account.
//
// API: POST /calendar/list (calendarList).
func (s *CalendarsService) CalendarList(ctx context.Context, req *CalendarListRequest) (*CalendarListResponse, *Response, error) {
	out := new(CalendarListResponse)
	resp, err := s.client.do(ctx, "/calendar/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update calendar.
//
// Update a personal service calendar. Only non-null fields are updated.
//
// API: POST /calendar/update (calendarUpdate).
func (s *CalendarsService) CalendarUpdate(ctx context.Context, req *CalendarUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/calendar/update", req, nil)
}
