// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ChangesService handles the "On-call/Changes" API resource.
type ChangesService service

// List changes.
//
// Query change records within a time window, with filtering, search, and pagination.
//
// API: POST /change/list (change-read-list).
func (s *ChangesService) List(ctx context.Context, req *ListChangeRequest) (*ListChangeResponse, *Response, error) {
	out := new(ListChangeResponse)
	resp, err := s.client.do(ctx, "/change/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
