// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// DataQueryService handles the "RUM/Data query" API resource.
type DataQueryService service

// Query RUM data.
//
// Run one or more SQL-style RUM data queries over a bounded time range.
//
// API: POST /rum/data/query (rum-read-data-query).
func (s *DataQueryService) Query(ctx context.Context, req *RUMDataQueryRequest) (*RUMDataQueryResponse, *Response, error) {
	out := new(RUMDataQueryResponse)
	resp, err := s.client.do(ctx, "/rum/data/query", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
