// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// DataSourcesService handles the "Monitors/Data sources" API resource.
type DataSourcesService service

// Get datasource detail.
//
// Retrieve full details of a single data source by its ID, including the `payload` configuration with its configured connection and authentication settings; treat the response as sensitive and avoid logging or forwarding it.
//
// API: POST /monit/datasource/info (monit-datasource-read-info).
func (s *DataSourcesService) ReadInfo(ctx context.Context, req *IDRequest) (*DataSourceItem, *Response, error) {
	out := new(DataSourceItem)
	resp, err := s.client.do(ctx, "/monit/datasource/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List datasources.
//
// Return all data sources for the current account. Optionally filter by `type_ident`.
//
// API: POST /monit/datasource/list (monit-datasource-read-list).
func (s *DataSourcesService) ReadList(ctx context.Context, req *DataSourceListRequest) (*DataSourceListResponse, *Response, error) {
	out := new(DataSourceListResponse)
	resp, err := s.client.do(ctx, "/monit/datasource/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List SLS logstores.
//
// List logstores within an SLS project for the specified SLS datasource.
//
// API: POST /monit/datasource/sls/logstores (monit-datasource-read-sls-logstores).
func (s *DataSourcesService) ReadSLSLogstores(ctx context.Context, req *SLSLogstoresRequest) (*SLSLogstoresResponse, *Response, error) {
	out := new(SLSLogstoresResponse)
	resp, err := s.client.do(ctx, "/monit/datasource/sls/logstores", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List SLS projects.
//
// List Alibaba Cloud SLS (Simple Log Service) projects available in the specified SLS datasource.
//
// API: POST /monit/datasource/sls/projects (monit-datasource-read-sls-projects).
func (s *DataSourcesService) ReadSLSProjects(ctx context.Context, req *SLSProjectsRequest) (*SLSProjectsResponse, *Response, error) {
	out := new(SLSProjectsResponse)
	resp, err := s.client.do(ctx, "/monit/datasource/sls/projects", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create datasource.
//
// Create a new monitoring data source. The `payload` must include the type-specific configuration block.
//
// API: POST /monit/datasource/create (monit-datasource-write-create).
func (s *DataSourcesService) WriteCreate(ctx context.Context, req *DataSourceUpsertRequest) (*DataSourceItem, *Response, error) {
	out := new(DataSourceItem)
	resp, err := s.client.do(ctx, "/monit/datasource/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete datasource.
//
// Delete a data source by ID. Alert rules referencing this datasource must be updated or deleted first.
//
// API: POST /monit/datasource/delete (monit-datasource-write-delete).
func (s *DataSourcesService) WriteDelete(ctx context.Context, req *IDRequest) (*Response, error) {
	return s.client.do(ctx, "/monit/datasource/delete", req, nil)
}

// Update datasource.
//
// Update an existing data source. Supply `id` plus the fields to change.
//
// API: POST /monit/datasource/update (monit-datasource-write-update).
func (s *DataSourcesService) WriteUpdate(ctx context.Context, req *DataSourceUpsertRequest) (*DataSourceItem, *Response, error) {
	out := new(DataSourceItem)
	resp, err := s.client.do(ctx, "/monit/datasource/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
