// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// DiagnosticsService handles the "Monitors/Diagnostics" API resource.
type DiagnosticsService service

// Query structured data.
//
// Run a synchronous ad-hoc query against a configured data source and return a stable `query_result.v1` result whose natural shape is frames, records, or samples. This public API requires monit-edge v0.65.0 or later.
//
// API: POST /monit/query/data (monit-read-query-data).
func (s *DiagnosticsService) QueryData(ctx context.Context, req *QueryDataRequest) (*QueryDataResponse, *Response, error) {
	out := new(QueryDataResponse)
	resp, err := s.client.do(ctx, "/monit/query/data", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Diagnose data source.
//
// Run a synchronous diagnostic query (`log_patterns` for Loki/VictoriaLogs, `metric_trends` for Prometheus). Used by Flashduty AI SRE for log-pattern clustering and time-series trend analysis. Long-running — up to 35 s.
//
// API: POST /monit/query/diagnose (monit-read-query-diagnose).
func (s *DiagnosticsService) QueryDiagnose(ctx context.Context, req *DiagnoseRequest) (*Response, error) {
	return s.client.do(ctx, "/monit/query/diagnose", req, nil)
}

// List monitored targets.
//
// List the targets observed under the current tenant by the monit-agent route projection. Supports `target_locator` prefix search and cursor pagination. Use this to drive `target_locator` selection for `/monit/tools/catalog` and `/monit/tools/invoke`.
//
// API: POST /monit/targets (monit-read-targets-list).
func (s *DiagnosticsService) TargetsList(ctx context.Context, req *TargetsListRequest) (*TargetsListResponse, *Response, error) {
	out := new(TargetsListResponse)
	resp, err := s.client.do(ctx, "/monit/targets", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List target tool catalog.
//
// Look up the tools that the per-target monit-agent currently exposes for a given `target_locator` (host, mysql, …). Returns each tool's name, description, and JSON-Schema `input_schema`. Pair with `/monit/tools/invoke` to drive AI-SRE tool calls.
//
// API: POST /monit/tools/catalog (monit-read-tools-catalog).
func (s *DiagnosticsService) ToolsCatalog(ctx context.Context, req *ToolCatalogRequest) (*ToolCatalogResponse, *Response, error) {
	out := new(ToolCatalogResponse)
	resp, err := s.client.do(ctx, "/monit/tools/catalog", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Invoke target tools.
//
// Invoke up to 8 monit-agent tools concurrently on a single target. Results come back in the order of the input `tools` array. Long-running — individual tools have per-tool timeouts on the agent and the whole request may take tens of seconds.
//
// API: POST /monit/tools/invoke (monit-read-tools-invoke).
func (s *DiagnosticsService) ToolsInvoke(ctx context.Context, req *ToolInvokeRequest) (*ToolInvokeResponse, *Response, error) {
	out := new(ToolInvokeResponse)
	resp, err := s.client.do(ctx, "/monit/tools/invoke", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
