// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// DiagnosticsService handles the "Monitors/Diagnostics" API resource.
type DiagnosticsService service

// Query structured data.
//
// Run a synchronous ad-hoc query against a configured data source and return a stable `query_result.v1` result whose natural shape is frames, records, or samples. This public API requires monit-edge v0.65.0 or later.
//
// API: POST /monit/query/data (monit-read-query-data).
func (s *DiagnosticsService) QueryData(ctx context.Context, req *QueryDataRequest) (*QueryDataResponse, *Response, error) {
	out := new(QueryDataResponse)
	resp, err := s.client.do(ctx, "/monit/query/data", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Diagnose data source.
//
// Run a synchronous diagnostic query (`log_patterns` for Loki/VictoriaLogs, `metric_trends` for Prometheus). Used by Flashduty AI SRE for log-pattern clustering and time-series trend analysis. Long-running — up to 35 s.
//
// Deprecated: migrate to /monit/datasource/tools/invoke with prometheus.metric_trends, loki.log_patterns or victorialogs.log_patterns. Retained for existing consumers; the legacy request and response remain unchanged.
//
// API: POST /monit/query/diagnose (monit-read-query-diagnose).
func (s *DiagnosticsService) QueryDiagnose(ctx context.Context, req *DiagnoseRequest) (*DiagnoseResponse, *Response, error) {
	out := new(DiagnoseResponse)
	resp, err := s.client.do(ctx, "/monit/query/diagnose", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
