// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// DiagnosticsService handles the "Monitors/Diagnostics" API resource.
type DiagnosticsService service

// Query structured data.
//
// Run a synchronous ad-hoc query against a configured data source and return a stable `query_result.v1` result whose natural shape is frames, records, or samples. This public API requires monit-edge v0.65.0 or later.
//
// API: POST /monit/query/data (monit-read-query-data).
func (s *DiagnosticsService) QueryData(ctx context.Context, req *QueryDataRequest) (*QueryDataResponse, *Response, error) {
	out := new(QueryDataResponse)
	resp, err := s.client.do(ctx, "/monit/query/data", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
