// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ErrorIngestionRulesService handles the "RUM/Error ingestion rules" API resource.
type ErrorIngestionRulesService service

// Create an error ingestion rule.
//
// Create a new error ingestion rule that filters which errors are stored.
//
// API: POST /rum/error-ingestion/rules/create (rum-error-ingestion-rules-create).
func (s *ErrorIngestionRulesService) Create(ctx context.Context, req *RUMErrorIngestionCreateRequest) (*RUMErrorIngestionCreateResponse, *Response, error) {
	out := new(RUMErrorIngestionCreateResponse)
	resp, err := s.client.do(ctx, "/rum/error-ingestion/rules/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete an error ingestion rule.
//
// Delete an error ingestion rule from a RUM application.
//
// API: POST /rum/error-ingestion/rules/delete (rum-error-ingestion-rules-delete).
func (s *ErrorIngestionRulesService) Delete(ctx context.Context, req *RUMErrorIngestionRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/error-ingestion/rules/delete", req, nil)
}

// Disable an error ingestion rule.
//
// Disable an error ingestion rule without deleting it.
//
// API: POST /rum/error-ingestion/rules/disable (rum-error-ingestion-rules-disable).
func (s *ErrorIngestionRulesService) Disable(ctx context.Context, req *RUMErrorIngestionRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/error-ingestion/rules/disable", req, nil)
}

// Enable an error ingestion rule.
//
// Re-enable a previously disabled error ingestion rule.
//
// API: POST /rum/error-ingestion/rules/enable (rum-error-ingestion-rules-enable).
func (s *ErrorIngestionRulesService) Enable(ctx context.Context, req *RUMErrorIngestionRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/error-ingestion/rules/enable", req, nil)
}

// List error ingestion rule history.
//
// Return paginated snapshots of an application's error ingestion rule history.
//
// API: POST /rum/error-ingestion/rules/history/list (rum-error-ingestion-rules-history-list).
func (s *ErrorIngestionRulesService) HistoryList(ctx context.Context, req *RUMErrorIngestionHistoryListRequest) (*RUMErrorIngestionHistoryListResponse, *Response, error) {
	out := new(RUMErrorIngestionHistoryListResponse)
	resp, err := s.client.do(ctx, "/rum/error-ingestion/rules/history/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Revert error ingestion rules to a history version.
//
// Restore an application's entire rule set to a prior history version.
//
// API: POST /rum/error-ingestion/rules/history/revert (rum-error-ingestion-rules-history-revert).
func (s *ErrorIngestionRulesService) HistoryRevert(ctx context.Context, req *RUMErrorIngestionRevertRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/error-ingestion/rules/history/revert", req, nil)
}

// List error ingestion rules.
//
// Return every error ingestion rule configured for a RUM application.
//
// API: POST /rum/error-ingestion/rules/list (rum-error-ingestion-rules-list).
func (s *ErrorIngestionRulesService) List(ctx context.Context, req *RUMErrorIngestionListRequest) (*RUMErrorIngestionListResponse, *Response, error) {
	out := new(RUMErrorIngestionListResponse)
	resp, err := s.client.do(ctx, "/rum/error-ingestion/rules/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update an error ingestion rule.
//
// Update the name, description, or filters of an error ingestion rule.
//
// API: POST /rum/error-ingestion/rules/update (rum-error-ingestion-rules-update).
func (s *ErrorIngestionRulesService) Update(ctx context.Context, req *RUMErrorIngestionUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/error-ingestion/rules/update", req, nil)
}
