// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// FacetsService handles the "RUM/Facets" API resource.
type FacetsService service

// Count facet value distribution.
//
// Return the top N values for a facet field within a time range, sorted by occurrence count descending.
//
// API: POST /rum/facet/count (rum-read-facet-count).
func (s *FacetsService) FacetCount(ctx context.Context, req *RUMFacetCountRequest) (*RUMFacetCountResponse, *Response, error) {
	out := new(RUMFacetCountResponse)
	resp, err := s.client.do(ctx, "/rum/facet/count", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List RUM facet fields.
//
// Return all available RUM field definitions, optionally filtered by scope and facet status.
//
// API: POST /rum/facet/list (rum-read-facet-list).
func (s *FacetsService) FacetList(ctx context.Context, req *RUMFacetListRequest) (*RUMFacetListResponse, *Response, error) {
	out := new(RUMFacetListResponse)
	resp, err := s.client.do(ctx, "/rum/facet/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List RUM fields.
//
// Return RUM field definitions, optionally filtered by scope and facet status.
//
// API: POST /rum/field/list (rum-read-field-list).
func (s *FacetsService) FieldList(ctx context.Context, req *RUMFieldListRequest) (*RUMFieldListResponse, *Response, error) {
	out := new(RUMFieldListResponse)
	resp, err := s.client.do(ctx, "/rum/field/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
