// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ImIntegrationsService handles the "On-call/IM integrations" API resource.
type ImIntegrationsService service

// List war-room-enabled IM integrations.
//
// List IM integrations that have the war-room feature enabled for the account.
//
// API: POST /datasource/im/war-room-enabled/list (im-war-room-enabled-list).
func (s *ImIntegrationsService) List(ctx context.Context) (*ListWarRoomEnabledResponse, *Response, error) {
	out := new(ListWarRoomEnabledResponse)
	resp, err := s.client.do(ctx, "/datasource/im/war-room-enabled/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
