// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// IncidentsService handles the "On-call/Incidents" API resource.
type IncidentsService service

// Get war-room default observers.
//
// Return historical responders suggested as default observers when opening a war room.
//
// API: POST /incident/war-room/default-observers (incident-read-get-war-room-default-observers).
func (s *IncidentsService) ReadGetWarRoomDefaultObservers(ctx context.Context, req *GetWarRoomDefaultObserversRequest) (*GetWarRoomDefaultObserversResponse, *Response, error) {
	out := new(GetWarRoomDefaultObserversResponse)
	resp, err := s.client.do(ctx, "/incident/war-room/default-observers", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Add war-room member.
//
// Add one or more members to the IM war room bound to an incident integration.
//
// API: POST /incident/war-room/add-member (incident-write-add-war-room-member).
func (s *IncidentsService) WriteAddWarRoomMember(ctx context.Context, req *AddWarRoomMemberRequest) (*string, *Response, error) {
	out := new(string)
	resp, err := s.client.do(ctx, "/incident/war-room/add-member", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Acknowledge incident.
//
// Acknowledge an incident to indicate you are actively working on it.
//
// API: POST /incident/ack (incidentAck).
func (s *IncidentsService) Ack(ctx context.Context, req *AckIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/ack", req, nil)
}

// List alerts of incident.
//
// List all alerts merged into a specific incident.
//
// API: POST /incident/alert/list (incidentAlertList).
func (s *IncidentsService) AlertList(ctx context.Context, req *ListIncidentAlertsRequest) (*ListIncidentAlertsResponse, *Response, error) {
	out := new(ListIncidentAlertsResponse)
	resp, err := s.client.do(ctx, "/incident/alert/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Assign incident.
//
// Dispatch an incident to a specific escalation level or responder.
//
// API: POST /incident/assign (incidentAssign).
func (s *IncidentsService) Assign(ctx context.Context, req *AssignIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/assign", req, nil)
}

// Add comment to incident.
//
// Add a text comment to the incident timeline.
//
// API: POST /incident/comment (incidentComment).
func (s *IncidentsService) Comment(ctx context.Context, req *CommentIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/comment", req, nil)
}

// Create incident.
//
// Manually create a new incident and assign responders.
//
// API: POST /incident/create (incidentCreate).
func (s *IncidentsService) Create(ctx context.Context, req *CreateIncidentRequest) (*CreateIncidentResponse, *Response, error) {
	out := new(CreateIncidentResponse)
	resp, err := s.client.do(ctx, "/incident/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Execute custom action.
//
// Execute a custom action configured for an incident.
//
// API: POST /incident/custom-action/do (incidentCustomActionDo).
func (s *IncidentsService) CustomActionDo(ctx context.Context, req *DoIncidentCustomActionRequest) (*DoIncidentCustomActionResponse, *Response, error) {
	out := new(DoIncidentCustomActionResponse)
	resp, err := s.client.do(ctx, "/incident/custom-action/do", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Disable incident merge.
//
// Disable automatic merging for a specific incident.
//
// API: POST /incident/disable-merge (incidentDisableMerge).
func (s *IncidentsService) DisableMerge(ctx context.Context, req *DisableIncidentMergeRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/disable-merge", req, nil)
}

// Get incident timeline.
//
// Retrieve the timeline feed for a specific incident, including state changes, comments and system events.
//
// API: POST /incident/feed (incidentFeed).
func (s *IncidentsService) Feed(ctx context.Context, req *ListIncidentFeedRequest) (*ListIncidentFeedResponse, *Response, error) {
	out := new(ListIncidentFeedResponse)
	resp, err := s.client.do(ctx, "/incident/feed", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update incident custom field.
//
// Update a custom field value on an incident.
//
// API: POST /incident/field/reset (incidentFieldReset).
func (s *IncidentsService) FieldReset(ctx context.Context, req *ResetIncidentFieldRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/field/reset", req, nil)
}

// Get incident detail.
//
// Retrieve detailed information for a single incident including timeline, alerts, responders and custom fields.
//
// API: POST /incident/info (incidentInfo).
func (s *IncidentsService) Info(ctx context.Context, req *IncidentInfoRequest) (*IncidentInfo, *Response, error) {
	out := new(IncidentInfo)
	resp, err := s.client.do(ctx, "/incident/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List incidents.
//
// Query a paginated list of incidents with filters by channel, severity, status, responder, and time range.
//
// API: POST /incident/list (incidentList).
func (s *IncidentsService) List(ctx context.Context, req *ListIncidentsRequest) (*IncidentListResponse, *Response, error) {
	out := new(IncidentListResponse)
	resp, err := s.client.do(ctx, "/incident/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List incidents by IDs.
//
// Retrieve multiple incidents by their IDs in a single request.
//
// API: POST /incident/list-by-ids (incidentListByIds).
func (s *IncidentsService) ListByIDs(ctx context.Context, req *ListIncidentsByIDsRequest) (*IncidentListResponse, *Response, error) {
	out := new(IncidentListResponse)
	resp, err := s.client.do(ctx, "/incident/list-by-ids", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Merge incidents.
//
// Merge one or more incidents into a target incident.
//
// API: POST /incident/merge (incidentMerge).
func (s *IncidentsService) Merge(ctx context.Context, req *MergeIncidentsRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/merge", req, nil)
}

// List past incidents.
//
// List historical incidents related to the current incident for reference during triage.
//
// API: POST /incident/past/list (incidentPastList).
func (s *IncidentsService) PastList(ctx context.Context, req *ListPastIncidentsRequest) (*ListPastIncidentsResponse, *Response, error) {
	out := new(ListPastIncidentsResponse)
	resp, err := s.client.do(ctx, "/incident/past/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete post-mortem.
//
// Delete a post-mortem report.
//
// API: POST /incident/post-mortem/delete (incidentPostMortemDelete).
func (s *IncidentsService) PostMortemDelete(ctx context.Context, req *DeletePostMortemRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/delete", req, nil)
}

// Get post-mortem.
//
// Retrieve a post-mortem report by its `post_mortem_id`. List reports via `/incident/post-mortem/list` first — each row carries the incident it covers — then fetch the full report here by that id.
//
// API: GET /incident/post-mortem/info (incidentPostMortemInfo).
func (s *IncidentsService) PostMortemInfo(ctx context.Context, req *IncidentsPostMortemInfoRequest) (*PostMortemItem, *Response, error) {
	out := new(PostMortemItem)
	resp, err := s.client.doGet(ctx, "/incident/post-mortem/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List post-mortems.
//
// List post-mortem reports with optional filters.
//
// API: POST /incident/post-mortem/list (incidentPostMortemList).
func (s *IncidentsService) PostMortemList(ctx context.Context, req *ListPostMortemsRequest) (*ListPostMortemsResponse, *Response, error) {
	out := new(ListPostMortemsResponse)
	resp, err := s.client.do(ctx, "/incident/post-mortem/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete an incident.
//
// Permanently delete an incident and all associated data.
//
// API: POST /incident/remove (incidentRemove).
func (s *IncidentsService) Remove(ctx context.Context, req *RemoveIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/remove", req, nil)
}

// Reopen incident.
//
// Reopen a previously resolved incident.
//
// API: POST /incident/reopen (incidentReopen).
func (s *IncidentsService) Reopen(ctx context.Context, req *ReopenIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/reopen", req, nil)
}

// Update incident fields.
//
// Update one or more editable fields of an incident in a single call, including title, description, impact, root cause, resolution, and severity. At least one field must be provided.
//
// API: POST /incident/reset (incidentReset).
func (s *IncidentsService) Reset(ctx context.Context, req *UpdateIncidentFieldsRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/reset", req, nil)
}

// Resolve incident.
//
// Mark an incident as resolved.
//
// API: POST /incident/resolve (incidentResolve).
func (s *IncidentsService) Resolve(ctx context.Context, req *ResolveIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/resolve", req, nil)
}

// Add incident responder.
//
// Add a responder to an existing incident.
//
// API: POST /incident/responder/add (incidentResponderAdd).
func (s *IncidentsService) ResponderAdd(ctx context.Context, req *AddIncidentResponderRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/responder/add", req, nil)
}

// Snooze incident.
//
// Temporarily snooze notifications for an incident until a specified time.
//
// API: POST /incident/snooze (incidentSnooze).
func (s *IncidentsService) Snooze(ctx context.Context, req *SnoozeIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/snooze", req, nil)
}

// Unacknowledge incident.
//
// Remove the acknowledge status from an incident.
//
// API: POST /incident/unack (incidentUnack).
func (s *IncidentsService) Unack(ctx context.Context, req *UnackIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/unack", req, nil)
}

// Wake incident.
//
// Cancel the snooze on an incident and resume notifications.
//
// API: POST /incident/wake (incidentWake).
func (s *IncidentsService) Wake(ctx context.Context, req *WakeIncidentRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/wake", req, nil)
}

// Create war room.
//
// Create a war room channel for collaborative incident response.
//
// API: POST /incident/war-room/create (incidentWarRoomCreate).
func (s *IncidentsService) WarRoomCreate(ctx context.Context, req *CreateWarRoomRequest) (*WarRoom, *Response, error) {
	out := new(WarRoom)
	resp, err := s.client.do(ctx, "/incident/war-room/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete war room.
//
// Delete an incident war room.
//
// API: POST /incident/war-room/delete (incidentWarRoomDelete).
func (s *IncidentsService) WarRoomDelete(ctx context.Context, req *DeleteWarRoomRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/war-room/delete", req, nil)
}

// Get war room detail.
//
// Retrieve the war room configuration and members for an incident.
//
// API: POST /incident/war-room/detail (incidentWarRoomDetail).
func (s *IncidentsService) WarRoomDetail(ctx context.Context, req *GetWarRoomDetailRequest) (*WarRoom, *Response, error) {
	out := new(WarRoom)
	resp, err := s.client.do(ctx, "/incident/war-room/detail", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List war rooms.
//
// List all war rooms associated with an incident.
//
// API: POST /incident/war-room/list (incidentWarRoomList).
func (s *IncidentsService) WarRoomList(ctx context.Context, req *ListWarRoomsRequest) (*ListWarRoomsResponse, *Response, error) {
	out := new(ListWarRoomsResponse)
	resp, err := s.client.do(ctx, "/incident/war-room/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List post-mortem templates.
//
// Return built-in and custom post-mortem templates for the account.
//
// API: POST /incident/post-mortem/template/list (postmortem-read-list-templates).
func (s *IncidentsService) PostmortemReadListTemplates(ctx context.Context, req *ListPostMortemTemplatesRequest) (*ListPostMortemTemplatesResponse, *Response, error) {
	out := new(ListPostMortemTemplatesResponse)
	resp, err := s.client.do(ctx, "/incident/post-mortem/template/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get post-mortem template detail.
//
// Return one post-mortem template by ID.
//
// API: GET /incident/post-mortem/template/info (postmortem-read-template-info).
func (s *IncidentsService) PostmortemReadTemplateInfo(ctx context.Context, req *IncidentsPostmortemReadTemplateInfoRequest) (*PostMortemTemplate, *Response, error) {
	out := new(PostMortemTemplate)
	resp, err := s.client.doGet(ctx, "/incident/post-mortem/template/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete post-mortem template.
//
// Delete a custom post-mortem template.
//
// API: POST /incident/post-mortem/template/delete (postmortem-write-delete-template).
func (s *IncidentsService) PostmortemWriteDeleteTemplate(ctx context.Context, req *DeletePostMortemTemplateRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/template/delete", req, nil)
}

// Initialize post-mortem.
//
// Create a post-mortem draft from one or more incidents and a template.
//
// API: POST /incident/post-mortem/init (postmortem-write-init).
func (s *IncidentsService) PostmortemWriteInit(ctx context.Context, req *InitPostMortemRequest) (*PostMortemItem, *Response, error) {
	out := new(PostMortemItem)
	resp, err := s.client.do(ctx, "/incident/post-mortem/init", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update post-mortem basics.
//
// Replace the incident facts stored in a post-mortem report.
//
// API: POST /incident/post-mortem/basics/reset (postmortem-write-reset-basics).
func (s *IncidentsService) PostmortemWriteResetBasics(ctx context.Context, req *ResetPostMortemBasicsRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/basics/reset", req, nil)
}

// Update post-mortem follow-ups.
//
// Replace the follow-up action items on a post-mortem report.
//
// API: POST /incident/post-mortem/follow-ups/reset (postmortem-write-reset-follow-ups).
func (s *IncidentsService) PostmortemWriteResetFollowUps(ctx context.Context, req *ResetPostMortemFollowUpsRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/follow-ups/reset", req, nil)
}

// Update post-mortem status.
//
// Set a post-mortem report to drafting or published.
//
// API: POST /incident/post-mortem/status/reset (postmortem-write-reset-status).
func (s *IncidentsService) PostmortemWriteResetStatus(ctx context.Context, req *ResetPostMortemStatusRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/status/reset", req, nil)
}

// Update post-mortem title.
//
// Replace the title of a post-mortem report.
//
// API: POST /incident/post-mortem/title/reset (postmortem-write-reset-title).
func (s *IncidentsService) PostmortemWriteResetTitle(ctx context.Context, req *ResetPostMortemTitleRequest) (*Response, error) {
	return s.client.do(ctx, "/incident/post-mortem/title/reset", req, nil)
}

// Create or update post-mortem template.
//
// Create a custom post-mortem template or update an existing one.
//
// API: POST /incident/post-mortem/template/upsert (postmortem-write-upsert-template).
func (s *IncidentsService) PostmortemWriteUpsertTemplate(ctx context.Context, req *UpsertPostMortemTemplateRequest) (*PostMortemTemplate, *Response, error) {
	out := new(PostMortemTemplate)
	resp, err := s.client.do(ctx, "/incident/post-mortem/template/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
