// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// IssuesService handles the "RUM/Issues" API resource.
type IssuesService service

// Export issues as CSV.
//
// Export the filtered RUM error tracking issues as a CSV file. The response is a `text/csv` stream delivered with `Content-Disposition: attachment` — it is not a JSON envelope; non-console callers can read the `X-Export-Total` and `X-Export-Truncated` response headers.
//
// The success body is a file, not a JSON envelope: it is returned on Response.Raw.
//
// API: POST /rum/issue/export (rum-issue-read-export).
func (s *IssuesService) ReadExport(ctx context.Context, req *RUMIssueExportRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/export", req, nil)
}

// Get issue detail.
//
// Retrieve full details of a single issue by `issue_id`.
//
// API: POST /rum/issue/info (rum-issue-read-info).
func (s *IssuesService) ReadInfo(ctx context.Context, req *RUMIssueIDRequest) (*RUMIssueItem, *Response, error) {
	out := new(RUMIssueItem)
	resp, err := s.client.do(ctx, "/rum/issue/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List issues.
//
// Return a paginated list of RUM error tracking issues matching the given filters.
//
// API: POST /rum/issue/list (rum-issue-read-list).
func (s *IssuesService) ReadList(ctx context.Context, req *RUMIssueListRequest) (*RUMIssueListResponse, *Response, error) {
	out := new(RUMIssueListResponse)
	resp, err := s.client.do(ctx, "/rum/issue/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update issue.
//
// Update the status or suspected cause of an issue.
//
// API: POST /rum/issue/update (rum-issue-write-update).
func (s *IssuesService) WriteUpdate(ctx context.Context, req *RUMIssueUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/update", req, nil)
}
