// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// IssuePresetSeverityRulesService handles the "RUM/Issue preset severity rules" API resource.
type IssuePresetSeverityRulesService service

// Create preset severity rule.
//
// Create a new preset severity rule for a RUM application.
//
// API: POST /rum/issue/preset-severity/rules/create (rum-issue-preset-severity-rules-create).
func (s *IssuePresetSeverityRulesService) Create(ctx context.Context, req *RUMPresetSeverityRuleCreateRequest) (*RUMPresetSeverityRuleCreateResponse, *Response, error) {
	out := new(RUMPresetSeverityRuleCreateResponse)
	resp, err := s.client.do(ctx, "/rum/issue/preset-severity/rules/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete preset severity rule.
//
// Delete a preset severity rule.
//
// API: POST /rum/issue/preset-severity/rules/delete (rum-issue-preset-severity-rules-delete).
func (s *IssuePresetSeverityRulesService) Delete(ctx context.Context, req *RUMPresetSeverityRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/delete", req, nil)
}

// Disable preset severity rule.
//
// Disable a preset severity rule.
//
// API: POST /rum/issue/preset-severity/rules/disable (rum-issue-preset-severity-rules-disable).
func (s *IssuePresetSeverityRulesService) Disable(ctx context.Context, req *RUMPresetSeverityRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/disable", req, nil)
}

// Enable preset severity rule.
//
// Enable a preset severity rule.
//
// API: POST /rum/issue/preset-severity/rules/enable (rum-issue-preset-severity-rules-enable).
func (s *IssuePresetSeverityRulesService) Enable(ctx context.Context, req *RUMPresetSeverityRuleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/enable", req, nil)
}

// List preset severity rule history.
//
// Return the change history of preset severity rules for a RUM application.
//
// API: POST /rum/issue/preset-severity/rules/history/list (rum-issue-preset-severity-rules-history-list).
func (s *IssuePresetSeverityRulesService) HistoryList(ctx context.Context, req *RUMPresetSeverityRuleHistoryListRequest) (*RUMPresetSeverityRuleHistoryListResponse, *Response, error) {
	out := new(RUMPresetSeverityRuleHistoryListResponse)
	resp, err := s.client.do(ctx, "/rum/issue/preset-severity/rules/history/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Revert preset severity rules to a history snapshot.
//
// Roll back preset severity rules to the state captured in a specific history snapshot.
//
// API: POST /rum/issue/preset-severity/rules/history/revert (rum-issue-preset-severity-rules-history-revert).
func (s *IssuePresetSeverityRulesService) HistoryRevert(ctx context.Context, req *RUMPresetSeverityRuleHistoryRevertRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/history/revert", req, nil)
}

// List preset severity rules.
//
// Return all preset severity rules configured for a RUM application.
//
// API: POST /rum/issue/preset-severity/rules/list (rum-issue-preset-severity-rules-list).
func (s *IssuePresetSeverityRulesService) List(ctx context.Context, req *RUMPresetSeverityRuleListRequest) (*RUMPresetSeverityRuleListResponse, *Response, error) {
	out := new(RUMPresetSeverityRuleListResponse)
	resp, err := s.client.do(ctx, "/rum/issue/preset-severity/rules/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Reorder preset severity rule.
//
// Move one preset severity rule to another rule's position in evaluation order.
//
// API: POST /rum/issue/preset-severity/rules/reorder (rum-issue-preset-severity-rules-reorder).
func (s *IssuePresetSeverityRulesService) Reorder(ctx context.Context, req *RUMPresetSeverityRuleReorderRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/reorder", req, nil)
}

// Update preset severity rule.
//
// Update the name, description, filters, or severity of a preset severity rule.
//
// API: POST /rum/issue/preset-severity/rules/update (rum-issue-preset-severity-rules-update).
func (s *IssuePresetSeverityRulesService) Update(ctx context.Context, req *RUMPresetSeverityRuleUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/rum/issue/preset-severity/rules/update", req, nil)
}
