// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// KnowledgeService handles the "AI SRE/Knowledge" API resource.
type KnowledgeService service

// Get knowledge file.
//
// Return a knowledge file's metadata and its base64-encoded content.
//
// API: POST /safari/knowledge/file/get (knowledge-file-read-get).
func (s *KnowledgeService) FileReadGet(ctx context.Context, req *KnowledgeFileGetRequest) (*KnowledgeFileGetResponse, *Response, error) {
	out := new(KnowledgeFileGetResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/file/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List knowledge files.
//
// List knowledge files with metadata such as size and checksum.
//
// API: POST /safari/knowledge/file/list (knowledge-file-read-list).
func (s *KnowledgeService) FileReadList(ctx context.Context, req *KnowledgeFileListRequest) (*KnowledgeFileListResponse, *Response, error) {
	out := new(KnowledgeFileListResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/file/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete knowledge file.
//
// Delete a knowledge file by its relative path.
//
// API: POST /safari/knowledge/file/delete (knowledge-file-write-delete).
func (s *KnowledgeService) FileWriteDelete(ctx context.Context, req *KnowledgeFileDeleteRequest) (*KnowledgeFileDeleteResponse, *Response, error) {
	out := new(KnowledgeFileDeleteResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/file/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Upload knowledge file.
//
// Create or overwrite a knowledge file with base64-encoded content.
//
// API: POST /safari/knowledge/file/put (knowledge-file-write-put).
func (s *KnowledgeService) FileWritePut(ctx context.Context, req *KnowledgeFilePutRequest) (*KnowledgeFilePutResponse, *Response, error) {
	out := new(KnowledgeFilePutResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/file/put", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get account knowledge.
//
// Return the metadata and file list of the account-scope knowledge.
//
// API: POST /safari/knowledge/get (knowledge-pack-read-get).
func (s *KnowledgeService) PackReadGet(ctx context.Context) (*KnowledgeGetResponse, *Response, error) {
	out := new(KnowledgeGetResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/get", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List knowledge.
//
// List the knowledge visible to the caller across account and team scopes.
//
// API: POST /safari/knowledge/pack/list (knowledge-pack-read-list).
func (s *KnowledgeService) PackReadList(ctx context.Context, req *KnowledgePackListRequest) (*KnowledgePackListResponse, *Response, error) {
	out := new(KnowledgePackListResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/pack/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete knowledge.
//
// Delete knowledge and all of its files.
//
// API: POST /safari/knowledge/pack/delete (knowledge-pack-write-delete).
func (s *KnowledgeService) PackWriteDelete(ctx context.Context, req *KnowledgePackDeleteRequest) (*KnowledgePackDeleteResponse, *Response, error) {
	out := new(KnowledgePackDeleteResponse)
	resp, err := s.client.do(ctx, "/safari/knowledge/pack/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Ensure knowledge.
//
// Idempotently create the knowledge at the given scope, or return the existing one.
//
// API: POST /safari/knowledge/pack/ensure (knowledge-pack-write-ensure).
func (s *KnowledgeService) PackWriteEnsure(ctx context.Context, req *KnowledgePackEnsureRequest) (*KnowledgePackItem, *Response, error) {
	out := new(KnowledgePackItem)
	resp, err := s.client.do(ctx, "/safari/knowledge/pack/ensure", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update knowledge.
//
// Move knowledge to a different account or team scope.
//
// API: POST /safari/knowledge/pack/update (knowledge-pack-write-update).
func (s *KnowledgeService) PackWriteUpdate(ctx context.Context, req *KnowledgePackUpdateRequest) (*KnowledgePackItem, *Response, error) {
	out := new(KnowledgePackItem)
	resp, err := s.client.do(ctx, "/safari/knowledge/pack/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
