// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// LicensesService handles the "On-call/Licenses" API resource.
type LicensesService service

// List On-call licenses.
//
// List people with active fixed or temporary On-call licenses in the current account.
//
// API: POST /oncall/license/list (oncall-license-read-license-list).
func (s *LicensesService) List(ctx context.Context) (*LicenseListResponse, *Response, error) {
	out := new(LicenseListResponse)
	resp, err := s.client.do(ctx, "/oncall/license/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
