// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// McpServersService handles the "AI SRE/MCP servers" API resource.
type McpServersService service

// Get MCP server detail.
//
// Return the full configuration of a single MCP server, with a live tool catalogue.
//
// API: POST /safari/mcp/server/get (mcp-read-server-get).
func (s *McpServersService) ReadServerGet(ctx context.Context, req *McpServerGetRequest) (*McpServerItem, *Response, error) {
	out := new(McpServerItem)
	resp, err := s.client.do(ctx, "/safari/mcp/server/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List MCP servers.
//
// List configured MCP servers visible to the caller across account and team scopes, with pagination.
//
// API: POST /safari/mcp/server/list (mcp-read-server-list).
func (s *McpServersService) ReadServerList(ctx context.Context, req *McpServerListRequest) (*McpServerListResponse, *Response, error) {
	out := new(McpServerListResponse)
	resp, err := s.client.do(ctx, "/safari/mcp/server/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create MCP server.
//
// Register a new MCP server the agent can call tools through.
//
// API: POST /safari/mcp/server/create (mcp-write-server-create).
func (s *McpServersService) WriteServerCreate(ctx context.Context, req *McpServerCreateRequest) (*McpServerItem, *Response, error) {
	out := new(McpServerItem)
	resp, err := s.client.do(ctx, "/safari/mcp/server/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete MCP server.
//
// Permanently remove an MCP server so agents can no longer use its tools.
//
// API: POST /safari/mcp/server/delete (mcp-write-server-delete).
func (s *McpServersService) WriteServerDelete(ctx context.Context, req *McpServerDeleteRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/mcp/server/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Disable MCP server.
//
// Deactivate an MCP server so agents stop calling its tools.
//
// API: POST /safari/mcp/server/disable (mcp-write-server-disable).
func (s *McpServersService) WriteServerDisable(ctx context.Context, req *McpServerStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/mcp/server/disable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Enable MCP server.
//
// Activate a disabled MCP server so agents can call its tools.
//
// API: POST /safari/mcp/server/enable (mcp-write-server-enable).
func (s *McpServersService) WriteServerEnable(ctx context.Context, req *McpServerStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/mcp/server/enable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update MCP server.
//
// Edit an MCP server's connection settings or reassign its owning team.
//
// API: POST /safari/mcp/server/update (mcp-write-server-update).
func (s *McpServersService) WriteServerUpdate(ctx context.Context, req *McpServerUpdateRequest) (*McpServerItem, *Response, error) {
	out := new(McpServerItem)
	resp, err := s.client.do(ctx, "/safari/mcp/server/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
