// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// MembersService handles the "Platform/Members" API resource.
type MembersService service

// Delete member.
//
// Remove a member from the organization by ID, email, phone, or name.
//
// API: POST /member/delete (memberDelete).
func (s *MembersService) MemberDelete(ctx context.Context, req *MemberDeleteRequest) (*Response, error) {
	return s.client.do(ctx, "/member/delete", req, nil)
}

// Grant role to member.
//
// Add a role assignment to a member.
//
// API: POST /member/role/grant (memberGrantRole).
func (s *MembersService) MemberGrantRole(ctx context.Context, req *MemberRoleGrantRequest) (*Response, error) {
	return s.client.do(ctx, "/member/role/grant", req, nil)
}

// Get current member info.
//
// Return the current session member's full profile.
//
// API: POST /member/info (memberInfo).
func (s *MembersService) MemberInfo(ctx context.Context) (*MemberInfoResponse, *Response, error) {
	out := new(MemberInfoResponse)
	resp, err := s.client.do(ctx, "/member/info", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Invite members.
//
// Batch invite new members to the organization by email or phone.
//
// API: POST /member/invite (memberInvite).
func (s *MembersService) MemberInvite(ctx context.Context, req *MemberInviteRequest) (*MemberInviteResponse, *Response, error) {
	out := new(MemberInviteResponse)
	resp, err := s.client.do(ctx, "/member/invite", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List members.
//
// Return a paginated list of organization members.
//
// API: POST /member/list (memberList).
func (s *MembersService) MemberList(ctx context.Context, req *MemberListRequest) (*MemberListResponse, *Response, error) {
	out := new(MemberListResponse)
	resp, err := s.client.do(ctx, "/member/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Reset member info.
//
// Batch-update multiple profile fields of the current member.
//
// API: POST /member/info/reset (memberResetInfo).
func (s *MembersService) MemberResetInfo(ctx context.Context, req *MemberResetInfoRequest) (*Response, error) {
	return s.client.do(ctx, "/member/info/reset", req, nil)
}

// Revoke role from member.
//
// Remove a role assignment from a member.
//
// API: POST /member/role/revoke (memberRevokeRole).
func (s *MembersService) MemberRevokeRole(ctx context.Context, req *MemberRoleRevokeRequest) (*Response, error) {
	return s.client.do(ctx, "/member/role/revoke", req, nil)
}

// Update member roles.
//
// Replace all role assignments for a member at once.
//
// API: POST /member/role/update (memberUpdateRole).
func (s *MembersService) MemberUpdateRole(ctx context.Context, req *MemberRoleUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/member/role/update", req, nil)
}

// Batch get persons.
//
// Return profile information for a batch of person IDs (members or accounts).
//
// API: POST /person/infos (personInfos).
func (s *MembersService) PersonInfos(ctx context.Context, req *PersonInfosRequest) (*PersonInfosResponse, *Response, error) {
	out := new(PersonInfosResponse)
	resp, err := s.client.do(ctx, "/person/infos", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
