// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// MonitorUtilitiesService handles the "Monitors/Monitor utilities" API resource.
type MonitorUtilitiesService service

// Preview datasource query.
//
// Execute a synchronous datasource query and return the raw result. Used to preview alert rule expressions before saving.
//
// API: POST /monit/preview/sync (monit-preview-sync).
func (s *MonitorUtilitiesService) Sync(ctx context.Context, req *PreviewSyncRequest) (*Response, error) {
	return s.client.do(ctx, "/monit/preview/sync", req, nil)
}
