// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// NotificationTemplatesService handles the "On-call/Notification templates" API resource.
type NotificationTemplatesService service

// Get template detail.
//
// Return a single notification template by ID.
//
// API: POST /template/info (template-read-info).
func (s *NotificationTemplatesService) ReadInfo(ctx context.Context, req *TemplateIDRequest) (*TemplateItem, *Response, error) {
	out := new(TemplateItem)
	resp, err := s.client.do(ctx, "/template/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List templates.
//
// Return a paginated list of notification templates.
//
// API: POST /template/list (template-read-list).
func (s *NotificationTemplatesService) ReadList(ctx context.Context, req *TemplateListRequest) (*TemplateListResponse, *Response, error) {
	out := new(TemplateListResponse)
	resp, err := s.client.do(ctx, "/template/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create a template.
//
// Create a new notification template.
//
// API: POST /template/create (template-write-create).
func (s *NotificationTemplatesService) WriteCreate(ctx context.Context, req *TemplateCreateRequest) (*TemplateCreateResponse, *Response, error) {
	out := new(TemplateCreateResponse)
	resp, err := s.client.do(ctx, "/template/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete a template.
//
// Soft-delete a template by ID.
//
// API: POST /template/delete (template-write-delete).
func (s *NotificationTemplatesService) WriteDelete(ctx context.Context, req *TemplateIDRequest) (*Response, error) {
	return s.client.do(ctx, "/template/delete", req, nil)
}

// Update a template.
//
// Replace the content of every channel on an existing template.
//
// API: POST /template/update (template-write-update).
func (s *NotificationTemplatesService) WriteUpdate(ctx context.Context, req *TemplateUpdateRequest) (*Response, error) {
	return s.client.do(ctx, "/template/update", req, nil)
}
