// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ResourcesService handles the "RUM/Resources" API resource.
type ResourcesService service

// Get RUM resource info.
//
// Return the account's RUM resource record and its current session usage.
//
// API: POST /rum/resource/info (rum-resource-read-info).
func (s *ResourcesService) Info(ctx context.Context, req *RUMResourceInfoRequest) (*RUMResourceItem, *Response, error) {
	out := new(RUMResourceItem)
	resp, err := s.client.do(ctx, "/rum/resource/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
