// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// RolesPermissionsService handles the "Platform/Roles & permissions" API resource.
type RolesPermissionsService service

// Get role detail.
//
// Return the detail of a single role by its ID.
//
// API: POST /role/info (role-read-info).
func (s *RolesPermissionsService) ReadInfo(ctx context.Context, req *RoleInfoRequest) (*RoleItem, *Response, error) {
	out := new(RoleItem)
	resp, err := s.client.do(ctx, "/role/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List roles.
//
// Return all custom and built-in roles for the current account.
//
// API: POST /role/list (role-read-list).
func (s *RolesPermissionsService) ReadList(ctx context.Context, req *RoleListRequest) (*RoleListResponse, *Response, error) {
	out := new(RoleListResponse)
	resp, err := s.client.do(ctx, "/role/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List permissions.
//
// Return all available permissions, optionally filtered to those granted to specific roles.
//
// API: POST /role/permission/list (role-read-list-permission).
func (s *RolesPermissionsService) ReadListPermission(ctx context.Context, req *RolePermissionListRequest) (*RolePermissionListResponse, *Response, error) {
	out := new(RolePermissionListResponse)
	resp, err := s.client.do(ctx, "/role/permission/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List permission factors.
//
// Return all permission factors (API, button, menu, URL, visit) granted to the calling member, optionally filtered by type. Requires a member-scoped credential — calls authenticated as the account principal (e.g. an account-level app key) are rejected with a 400, because the account principal implicitly holds every permission.
//
// API: POST /role/permission/factor/list (role-read-list-permission-factor).
func (s *RolesPermissionsService) ReadListPermissionFactor(ctx context.Context, req *PermissionFactorListRequest) (*PermissionFactorListResponse, *Response, error) {
	out := new(PermissionFactorListResponse)
	resp, err := s.client.do(ctx, "/role/permission/factor/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete a role.
//
// Delete a custom role. While members still hold the role, the call fails with `ReferenceExist` unless `is_force` is true.
//
// API: POST /role/delete (role-write-delete).
func (s *RolesPermissionsService) WriteDelete(ctx context.Context, req *RoleDeleteRequest) (*Response, error) {
	return s.client.do(ctx, "/role/delete", req, nil)
}

// Disable a role.
//
// Disable a custom role to prevent it from granting permissions.
//
// API: POST /role/disable (role-write-disable).
func (s *RolesPermissionsService) WriteDisable(ctx context.Context, req *RoleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/role/disable", req, nil)
}

// Enable a role.
//
// Re-enable a previously disabled custom role.
//
// API: POST /role/enable (role-write-enable).
func (s *RolesPermissionsService) WriteEnable(ctx context.Context, req *RoleIDRequest) (*Response, error) {
	return s.client.do(ctx, "/role/enable", req, nil)
}

// Grant role to members.
//
// Assign a role to one or more members, giving them its permissions.
//
// API: POST /role/member/grant (role-write-grant-role).
func (s *RolesPermissionsService) WriteGrantRole(ctx context.Context, req *RoleGrantRequest) (*Response, error) {
	return s.client.do(ctx, "/role/member/grant", req, nil)
}

// Revoke role from members.
//
// Remove a role from one or more members, revoking the permissions it granted.
//
// API: POST /role/member/revoke (role-write-revoke-role).
func (s *RolesPermissionsService) WriteRevokeRole(ctx context.Context, req *RoleGrantRequest) (*Response, error) {
	return s.client.do(ctx, "/role/member/revoke", req, nil)
}

// Create or update a role.
//
// Create a new custom role or update an existing one. Pass `role_id` to update.
//
// API: POST /role/upsert (role-write-upsert).
func (s *RolesPermissionsService) WriteUpsert(ctx context.Context, req *RoleUpsertRequest) (*RoleUpsertResponse, *Response, error) {
	out := new(RoleUpsertResponse)
	resp, err := s.client.do(ctx, "/role/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
