// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// RuleSetsService handles the "Monitors/Rule sets" API resource.
type RuleSetsService service

// Create ruleset.
//
// Create a new ruleset in the rule repository.
//
// API: POST /monit/store/ruleset/create (monit-store-ruleset-create).
func (s *RuleSetsService) Create(ctx context.Context, req *StoreRulesetUpsertRequest) (*StoreRulesetItem, *Response, error) {
	out := new(StoreRulesetItem)
	resp, err := s.client.do(ctx, "/monit/store/ruleset/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete ruleset.
//
// Delete a ruleset from the rule repository by ID.
//
// API: POST /monit/store/ruleset/delete (monit-store-ruleset-delete).
func (s *RuleSetsService) Delete(ctx context.Context, req *IDRequest) (*Response, error) {
	return s.client.do(ctx, "/monit/store/ruleset/delete", req, nil)
}

// Get ruleset detail.
//
// Retrieve the full details of a ruleset including its `payload` (the alert rule definitions as a JSON string).
//
// API: POST /monit/store/ruleset/info (monit-store-ruleset-info).
func (s *RuleSetsService) Info(ctx context.Context, req *IDRequest) (*StoreRulesetItem, *Response, error) {
	out := new(StoreRulesetItem)
	resp, err := s.client.do(ctx, "/monit/store/ruleset/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List rulesets.
//
// Return all rulesets for a given datasource type that are accessible to the current user.
//
// API: POST /monit/store/ruleset/list (monit-store-ruleset-list).
func (s *RuleSetsService) List(ctx context.Context, req *StoreRulesetListRequest) (*StoreRulesetListResponse, *Response, error) {
	out := new(StoreRulesetListResponse)
	resp, err := s.client.do(ctx, "/monit/store/ruleset/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update ruleset.
//
// Update the note, sharing flag, and payload of an existing ruleset.
//
// API: POST /monit/store/ruleset/update (monit-store-ruleset-update).
func (s *RuleSetsService) Update(ctx context.Context, req *StoreRulesetUpdateRequest) (*StoreRulesetItem, *Response, error) {
	out := new(StoreRulesetItem)
	resp, err := s.client.do(ctx, "/monit/store/ruleset/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
