// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// RuleFoldersService handles the "Monitors/Rule folders" API resource.
type RuleFoldersService service

// List monitor folders.
//
// List every monitor folder the caller can read.
//
// API: POST /monit/folder/list (monit-folder-read-list).
func (s *RuleFoldersService) List(ctx context.Context) (*[]FolderItem, *Response, error) {
	out := new([]FolderItem)
	resp, err := s.client.do(ctx, "/monit/folder/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
