// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

// service is the shared backing for every typed service; all services view
// the same Client through it (one allocation).
type service struct{ client *Client }

// genServices is embedded in Client to expose the generated service handles.
type genServices struct {
	AlertRules            *AlertRulesService
	DataSources           *DataSourcesService
	Diagnostics           *DiagnosticsService
	RuleSets              *RuleSetsService
	AlertEnrichment       *AlertEnrichmentService
	Alerts                *AlertsService
	Analytics             *AnalyticsService
	Calendars             *CalendarsService
	Channels              *ChannelsService
	Incidents             *IncidentsService
	Integrations          *IntegrationsService
	NotificationTemplates *NotificationTemplatesService
	Schedules             *SchedulesService
	StatusPages           *StatusPagesService
	AuditLogs             *AuditLogsService
	Members               *MembersService
	RolesPermissions      *RolesPermissionsService
	Teams                 *TeamsService
	Applications          *ApplicationsService
	Issues                *IssuesService
	Sourcemaps            *SourcemapsService
}

// initServices wires every service to the shared backref. Called by NewClient.
func (c *Client) initServices() {
	c.common.client = c
	c.AlertRules = (*AlertRulesService)(&c.common)
	c.DataSources = (*DataSourcesService)(&c.common)
	c.Diagnostics = (*DiagnosticsService)(&c.common)
	c.RuleSets = (*RuleSetsService)(&c.common)
	c.AlertEnrichment = (*AlertEnrichmentService)(&c.common)
	c.Alerts = (*AlertsService)(&c.common)
	c.Analytics = (*AnalyticsService)(&c.common)
	c.Calendars = (*CalendarsService)(&c.common)
	c.Channels = (*ChannelsService)(&c.common)
	c.Incidents = (*IncidentsService)(&c.common)
	c.Integrations = (*IntegrationsService)(&c.common)
	c.NotificationTemplates = (*NotificationTemplatesService)(&c.common)
	c.Schedules = (*SchedulesService)(&c.common)
	c.StatusPages = (*StatusPagesService)(&c.common)
	c.AuditLogs = (*AuditLogsService)(&c.common)
	c.Members = (*MembersService)(&c.common)
	c.RolesPermissions = (*RolesPermissionsService)(&c.common)
	c.Teams = (*TeamsService)(&c.common)
	c.Applications = (*ApplicationsService)(&c.common)
	c.Issues = (*IssuesService)(&c.common)
	c.Sourcemaps = (*SourcemapsService)(&c.common)
}
