// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// ServiceMapService handles the "Monitors/Service map" API resource.
type ServiceMapService service

// Browse service map fleet hosts.
//
// Browse the account's hosts with ServiceMap capability and current collection status.
//
// API: POST /monit/servicemap/fleet (monit-servicemap-read-fleet).
func (s *ServiceMapService) Fleet(ctx context.Context, req *ServiceMapFleetBrowseRequest) (*ServiceMapFleetBrowseResponse, *Response, error) {
	out := new(ServiceMapFleetBrowseResponse)
	resp, err := s.client.do(ctx, "/monit/servicemap/fleet", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get service map fleet summary.
//
// Return an aggregate status distribution across the account's ServiceMap-capable hosts.
//
// API: POST /monit/servicemap/fleet/summary (monit-servicemap-read-fleet-summary).
func (s *ServiceMapService) FleetSummary(ctx context.Context, req *ServiceMapFleetSummaryRequest) (*ServiceMapFleetSummaryResponse, *Response, error) {
	out := new(ServiceMapFleetSummaryResponse)
	resp, err := s.client.do(ctx, "/monit/servicemap/fleet/summary", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get service map status.
//
// Return ServiceMap collection status for one or more hosts, or a bounded fleet sample.
//
// API: POST /monit/servicemap/status (monit-servicemap-read-status).
func (s *ServiceMapService) Status(ctx context.Context, req *ServiceMapStatusRequest) (*ServiceMapStatusResponse, *Response, error) {
	out := new(ServiceMapStatusResponse)
	resp, err := s.client.do(ctx, "/monit/servicemap/status", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get service map summary.
//
// Return a bounded, AI-ready summary of a host's outbound service dependencies.
//
// API: POST /monit/servicemap/summary (monit-servicemap-read-summary).
func (s *ServiceMapService) Summary(ctx context.Context, req *ServiceMapSummaryRequest) (*ServiceMapSummaryResponse, *Response, error) {
	out := new(ServiceMapSummaryResponse)
	resp, err := s.client.do(ctx, "/monit/servicemap/summary", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get service map topology.
//
// Return the outbound dependency graph around a host, discovered by live network observation.
//
// API: POST /monit/servicemap/topology (monit-servicemap-read-topology).
func (s *ServiceMapService) Topology(ctx context.Context, req *ServiceMapTopologyRequest) (*ServiceMapTopologyResponse, *Response, error) {
	out := new(ServiceMapTopologyResponse)
	resp, err := s.client.do(ctx, "/monit/servicemap/topology", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
