// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

// service is the shared backing for every typed service; all services view
// the same Client through it (one allocation).
type service struct{ client *Client }

// genServices is embedded in Client to expose the generated service handles.
type genServices struct {
	A2aAgents                *A2aAgentsService
	Automations              *AutomationsService
	Knowledge                *KnowledgeService
	McpServers               *McpServersService
	Sessions                 *SessionsService
	Skills                   *SkillsService
	AlertRules               *AlertRulesService
	DataSources              *DataSourcesService
	Diagnostics              *DiagnosticsService
	MonitorUtilities         *MonitorUtilitiesService
	RuleSets                 *RuleSetsService
	ServiceMap               *ServiceMapService
	AlertEnrichment          *AlertEnrichmentService
	Alerts                   *AlertsService
	Analytics                *AnalyticsService
	Calendars                *CalendarsService
	Changes                  *ChangesService
	Channels                 *ChannelsService
	ImIntegrations           *ImIntegrationsService
	Incidents                *IncidentsService
	Integrations             *IntegrationsService
	Licenses                 *LicensesService
	NotificationTemplates    *NotificationTemplatesService
	Schedules                *SchedulesService
	StatusPages              *StatusPagesService
	Account                  *AccountService
	AuditLogs                *AuditLogsService
	Members                  *MembersService
	RolesPermissions         *RolesPermissionsService
	Teams                    *TeamsService
	Applications             *ApplicationsService
	DataQuery                *DataQueryService
	ErrorIngestionRules      *ErrorIngestionRulesService
	Facets                   *FacetsService
	IssuePresetSeverityRules *IssuePresetSeverityRulesService
	Issues                   *IssuesService
	Resources                *ResourcesService
	SessionReplay            *SessionReplayService
	Sourcemaps               *SourcemapsService
}

// initServices wires every service to the shared backref. Called by NewClient.
func (c *Client) initServices() {
	c.common.client = c
	c.A2aAgents = (*A2aAgentsService)(&c.common)
	c.Automations = (*AutomationsService)(&c.common)
	c.Knowledge = (*KnowledgeService)(&c.common)
	c.McpServers = (*McpServersService)(&c.common)
	c.Sessions = (*SessionsService)(&c.common)
	c.Skills = (*SkillsService)(&c.common)
	c.AlertRules = (*AlertRulesService)(&c.common)
	c.DataSources = (*DataSourcesService)(&c.common)
	c.Diagnostics = (*DiagnosticsService)(&c.common)
	c.MonitorUtilities = (*MonitorUtilitiesService)(&c.common)
	c.RuleSets = (*RuleSetsService)(&c.common)
	c.ServiceMap = (*ServiceMapService)(&c.common)
	c.AlertEnrichment = (*AlertEnrichmentService)(&c.common)
	c.Alerts = (*AlertsService)(&c.common)
	c.Analytics = (*AnalyticsService)(&c.common)
	c.Calendars = (*CalendarsService)(&c.common)
	c.Changes = (*ChangesService)(&c.common)
	c.Channels = (*ChannelsService)(&c.common)
	c.ImIntegrations = (*ImIntegrationsService)(&c.common)
	c.Incidents = (*IncidentsService)(&c.common)
	c.Integrations = (*IntegrationsService)(&c.common)
	c.Licenses = (*LicensesService)(&c.common)
	c.NotificationTemplates = (*NotificationTemplatesService)(&c.common)
	c.Schedules = (*SchedulesService)(&c.common)
	c.StatusPages = (*StatusPagesService)(&c.common)
	c.Account = (*AccountService)(&c.common)
	c.AuditLogs = (*AuditLogsService)(&c.common)
	c.Members = (*MembersService)(&c.common)
	c.RolesPermissions = (*RolesPermissionsService)(&c.common)
	c.Teams = (*TeamsService)(&c.common)
	c.Applications = (*ApplicationsService)(&c.common)
	c.DataQuery = (*DataQueryService)(&c.common)
	c.ErrorIngestionRules = (*ErrorIngestionRulesService)(&c.common)
	c.Facets = (*FacetsService)(&c.common)
	c.IssuePresetSeverityRules = (*IssuePresetSeverityRulesService)(&c.common)
	c.Issues = (*IssuesService)(&c.common)
	c.Resources = (*ResourcesService)(&c.common)
	c.SessionReplay = (*SessionReplayService)(&c.common)
	c.Sourcemaps = (*SourcemapsService)(&c.common)
}
