// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// SessionsService handles the "AI SRE/Sessions" API resource.
type SessionsService service

// Get session detail.
//
// Fetch one session plus a backward-paged window of its most recent events.
//
// API: POST /safari/session/get (session-read-info).
func (s *SessionsService) ReadInfo(ctx context.Context, req *SessionGetRequest) (*SessionGetResponse, *Response, error) {
	out := new(SessionGetResponse)
	resp, err := s.client.do(ctx, "/safari/session/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List sessions.
//
// List agent sessions visible to the caller, filtered by app, surface, archive status, and team.
//
// API: POST /safari/session/list (session-read-list).
func (s *SessionsService) ReadList(ctx context.Context, req *SessionListRequest) (*SessionListResponse, *Response, error) {
	out := new(SessionListResponse)
	resp, err := s.client.do(ctx, "/safari/session/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete session.
//
// Delete a session by ID.
//
// API: POST /safari/session/delete (session-write-delete).
func (s *SessionsService) WriteDelete(ctx context.Context, req *SessionDeleteRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/session/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
