// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// SessionReplayService handles the "RUM/Session replay" API resource.
type SessionReplayService service

// Get session replay metadata.
//
// Return the application, device, session bounds, and views recorded for a replayable session.
//
// API: POST /rum/session-replay/metadata (rum-session-replay-read-metadata).
func (s *SessionReplayService) Metadata(ctx context.Context, req *RUMSessionReplayMetaRequest) (*RUMSessionReplayMetaItem, *Response, error) {
	out := new(RUMSessionReplayMetaItem)
	resp, err := s.client.do(ctx, "/rum/session-replay/metadata", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List session replay segments.
//
// Page through the recorded replay segments of a session, as presigned URLs or a raw stream.
//
// API: POST /rum/session-replay/segments (rum-session-replay-read-segments).
func (s *SessionReplayService) Segments(ctx context.Context, req *RUMSessionReplaySegmentsRequest) (*RUMSessionReplaySegmentsResult, *Response, error) {
	out := new(RUMSessionReplaySegmentsResult)
	resp, err := s.client.do(ctx, "/rum/session-replay/segments", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
