// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// SkillsService handles the "AI SRE/Skills" API resource.
type SkillsService service

// Download skill.
//
// Download the original zip package of a skill as a binary attachment.
//
// API: POST /safari/skill/download (skill-read-download).
func (s *SkillsService) ReadDownload(ctx context.Context, req *SkillDownloadRequest) (*string, *Response, error) {
	out := new(string)
	resp, err := s.client.do(ctx, "/safari/skill/download", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Enable skill.
//
// Activate a disabled skill so agents can load it at session start.
//
// API: POST /safari/skill/enable (skill-read-enable).
func (s *SkillsService) ReadEnable(ctx context.Context, req *SkillStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/enable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get skill detail.
//
// Return the full configuration and SKILL.md body of a single skill by ID.
//
// API: POST /safari/skill/get (skill-read-get).
func (s *SkillsService) ReadGet(ctx context.Context, req *SkillGetRequest) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List skills.
//
// List AI SRE skills visible to the caller across account and team scopes, with pagination.
//
// API: POST /safari/skill/list (skill-read-list).
func (s *SkillsService) ReadList(ctx context.Context, req *SkillListRequest) (*SkillListResponse, *Response, error) {
	out := new(SkillListResponse)
	resp, err := s.client.do(ctx, "/safari/skill/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete skill.
//
// Permanently remove a skill so agents can no longer load it.
//
// API: POST /safari/skill/delete (skill-write-delete).
func (s *SkillsService) WriteDelete(ctx context.Context, req *SkillDeleteRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Disable skill.
//
// Deactivate an enabled skill so agents no longer load it.
//
// API: POST /safari/skill/disable (skill-write-disable).
func (s *SkillsService) WriteDisable(ctx context.Context, req *SkillStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/disable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update skill.
//
// Edit a skill's description or reassign its owning team.
//
// API: POST /safari/skill/update (skill-write-update).
func (s *SkillsService) WriteUpdate(ctx context.Context, req *SkillUpdateRequest) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Upload skill.
//
// Upload a skill zip package and register it as a new account or team skill.
//
// API: POST /safari/skill/upload (skill-write-upload).
func (s *SkillsService) WriteUpload(ctx context.Context) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/upload", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
