// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// SkillsService handles the "AI SRE/Skills" API resource.
type SkillsService service

// Enable skill.
//
// Enable a disabled skill so the agent can load it.
//
// API: POST /safari/skill/enable (skill-read-enable).
func (s *SkillsService) ReadEnable(ctx context.Context, req *SkillStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/enable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Get skill detail.
//
// Get one skill including its full SKILL.md content.
//
// API: POST /safari/skill/get (skill-read-get).
func (s *SkillsService) ReadGet(ctx context.Context, req *SkillGetRequest) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/get", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List skills.
//
// List AI SRE skills visible to the caller across account and team scopes, with pagination.
//
// API: POST /safari/skill/list (skill-read-list).
func (s *SkillsService) ReadList(ctx context.Context, req *SkillListRequest) (*SkillListResponse, *Response, error) {
	out := new(SkillListResponse)
	resp, err := s.client.do(ctx, "/safari/skill/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete skill.
//
// Delete a skill by ID.
//
// API: POST /safari/skill/delete (skill-write-delete).
func (s *SkillsService) WriteDelete(ctx context.Context, req *SkillDeleteRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/delete", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Disable skill.
//
// Disable an enabled skill so the agent stops loading it.
//
// API: POST /safari/skill/disable (skill-write-disable).
func (s *SkillsService) WriteDisable(ctx context.Context, req *SkillStatusRequest) (*any, *Response, error) {
	out := new(any)
	resp, err := s.client.do(ctx, "/safari/skill/disable", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update skill.
//
// Update a skill's descriptions or reassign its team scope.
//
// API: POST /safari/skill/update (skill-write-update).
func (s *SkillsService) WriteUpdate(ctx context.Context, req *SkillUpdateRequest) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/update", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Upload skill.
//
// Upload a skill archive (.skill/.zip/.tar.gz/.tgz) to create or replace a skill.
//
// API: POST /safari/skill/upload (skill-write-upload).
func (s *SkillsService) WriteUpload(ctx context.Context) (*SkillItem, *Response, error) {
	out := new(SkillItem)
	resp, err := s.client.do(ctx, "/safari/skill/upload", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
