// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// SourcemapsService handles the "RUM/Sourcemaps" API resource.
type SourcemapsService service

// List sourcemaps.
//
// Return a paginated list of uploaded sourcemap files filtered by platform type, service, and version.
//
// API: POST /sourcemap/list (sourcemap-read-list).
func (s *SourcemapsService) List(ctx context.Context, req *SourcemapListRequest) (*SourcemapListResponse, *Response, error) {
	out := new(SourcemapListResponse)
	resp, err := s.client.do(ctx, "/sourcemap/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Enrich a stack trace.
//
// Symbolicate or deobfuscate a browser, Android, iOS, Mini Program, or HarmonyOS stack trace.
//
// API: POST /sourcemap/stack/enrich (sourcemap-read-stack-enrich).
func (s *SourcemapsService) StackEnrich(ctx context.Context, req *SourcemapStackEnrichRequest) (*SourcemapStackEnrichResponse, *Response, error) {
	out := new(SourcemapStackEnrichResponse)
	resp, err := s.client.do(ctx, "/sourcemap/stack/enrich", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
