// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// StatusPagesService handles the "On-call/Status pages" API resource.
type StatusPagesService service

// List status pages.
//
// List all status pages owned by the account, including their components and sections.
//
// API: GET /status-page/list (status-page-read-page-list).
func (s *StatusPagesService) ReadPageList(ctx context.Context) (*ListStatusPageResponse, *Response, error) {
	out := new(ListStatusPageResponse)
	resp, err := s.client.doGet(ctx, "/status-page/list", nil, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List active status page events.
//
// List in-progress (non-terminal) events of a given type for a status page.
//
// API: GET /status-page/change/active/list (statusPageChangeActiveList).
func (s *StatusPagesService) ChangeActiveList(ctx context.Context, req *StatusPagesChangeActiveListRequest) (*StatusPageChangeListResponse, *Response, error) {
	out := new(StatusPageChangeListResponse)
	resp, err := s.client.doGet(ctx, "/status-page/change/active/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create status page event.
//
// Create a new incident or maintenance event on a status page.
//
// API: POST /status-page/change/create (statusPageChangeCreate).
func (s *StatusPagesService) ChangeCreate(ctx context.Context, req *CreateStatusPageChangeRequest) (*StatusPageChangeCreateResponse, *Response, error) {
	out := new(StatusPageChangeCreateResponse)
	resp, err := s.client.do(ctx, "/status-page/change/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete status page event.
//
// Delete a status page event.
//
// API: POST /status-page/change/delete (statusPageChangeDelete).
func (s *StatusPagesService) ChangeDelete(ctx context.Context, req *DeleteStatusPageChangeRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/change/delete", req, nil)
}

// Get status page event detail.
//
// Retrieve details of a specific status page event (incident or maintenance).
//
// API: GET /status-page/change/info (statusPageChangeInfo).
func (s *StatusPagesService) ChangeInfo(ctx context.Context, req *StatusPagesChangeInfoRequest) (*StatusPageChangeItem, *Response, error) {
	out := new(StatusPageChangeItem)
	resp, err := s.client.doGet(ctx, "/status-page/change/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List status page events.
//
// List status page events with only publicly visible affected components.
//
// API: GET /status-page/change/list (statusPageChangeList).
func (s *StatusPagesService) ChangeList(ctx context.Context, req *StatusPagesChangeListRequest) (*StatusPageChangeListResponse, *Response, error) {
	out := new(StatusPageChangeListResponse)
	resp, err := s.client.doGet(ctx, "/status-page/change/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create event timeline entry.
//
// Add a timeline update to a status page event.
//
// API: POST /status-page/change/timeline/create (statusPageChangeTimelineCreate).
func (s *StatusPagesService) ChangeTimelineCreate(ctx context.Context, req *CreateStatusPageChangeTimelineRequest) (*StatusPageChangeTimelineCreateResponse, *Response, error) {
	out := new(StatusPageChangeTimelineCreateResponse)
	resp, err := s.client.do(ctx, "/status-page/change/timeline/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete event timeline entry.
//
// Delete a timeline entry from a status page event.
//
// API: POST /status-page/change/timeline/delete (statusPageChangeTimelineDelete).
func (s *StatusPagesService) ChangeTimelineDelete(ctx context.Context, req *DeleteStatusPageChangeTimelineRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/change/timeline/delete", req, nil)
}

// Update event timeline entry.
//
// Update a timeline entry for a status page event.
//
// API: POST /status-page/change/timeline/update (statusPageChangeTimelineUpdate).
func (s *StatusPagesService) ChangeTimelineUpdate(ctx context.Context, req *UpdateStatusPageChangeTimelineRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/change/timeline/update", req, nil)
}

// Update status page event.
//
// Update an existing status page event.
//
// API: POST /status-page/change/update (statusPageChangeUpdate).
func (s *StatusPagesService) ChangeUpdate(ctx context.Context, req *UpdateStatusPageChangeRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/change/update", req, nil)
}

// Delete status page component.
//
// Delete a service component from a status page.
//
// API: POST /status-page/component/delete (statusPageComponentDelete).
func (s *StatusPagesService) ComponentDelete(ctx context.Context, req *DeleteStatusPageComponentRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/component/delete", req, nil)
}

// Upsert status page component.
//
// Create or update a service component on a status page.
//
// API: POST /status-page/component/upsert (statusPageComponentUpsert).
func (s *StatusPagesService) ComponentUpsert(ctx context.Context, req *UpsertStatusPageComponentRequest) (*UpsertStatusPageComponentResponse, *Response, error) {
	out := new(UpsertStatusPageComponentResponse)
	resp, err := s.client.do(ctx, "/status-page/component/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Create status page.
//
// Create a new status page.
//
// API: POST /status-page/create (statusPageCreate).
func (s *StatusPagesService) Create(ctx context.Context, req *CreateStatusPageRequest) (*CreateStatusPageResponse, *Response, error) {
	out := new(CreateStatusPageResponse)
	resp, err := s.client.do(ctx, "/status-page/create", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete status page.
//
// Delete a status page.
//
// API: POST /status-page/delete (statusPageDelete).
func (s *StatusPagesService) Delete(ctx context.Context, req *DeleteStatusPageRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/delete", req, nil)
}

// Get status page detail.
//
// Retrieve detailed configuration for a specific status page.
//
// API: GET /status-page/info (statusPageInfo).
func (s *StatusPagesService) Info(ctx context.Context, req *StatusPagesInfoRequest) (*Response, error) {
	return s.client.doGet(ctx, "/status-page/info", req, nil)
}

// Migrate email subscribers.
//
// Start a migration job that imports email subscribers from an Atlassian Statuspage into an existing Flashduty status page.
//
// API: POST /status-page/migrate-email-subscribers (statusPageMigrateEmailSubscribers).
func (s *StatusPagesService) MigrateEmailSubscribers(ctx context.Context, req *MigrateStatusPageEmailSubscribersRequest) (*StatusPageMigrationStartResponse, *Response, error) {
	out := new(StatusPageMigrationStartResponse)
	resp, err := s.client.do(ctx, "/status-page/migrate-email-subscribers", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Migrate status page structure.
//
// Start a migration job that imports the structure and historical events of an Atlassian Statuspage into a new Flashduty status page.
//
// API: POST /status-page/migrate-structure (statusPageMigrateStructure).
func (s *StatusPagesService) MigrateStructure(ctx context.Context, req *MigrateStatusPageStructureRequest) (*StatusPageMigrationStartResponse, *Response, error) {
	out := new(StatusPageMigrationStartResponse)
	resp, err := s.client.do(ctx, "/status-page/migrate-structure", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Cancel status page migration.
//
// Cancel an in-progress status page migration job. Only jobs currently in the `running` state can be cancelled.
//
// API: POST /status-page/migration/cancel (statusPageMigrationCancel).
func (s *StatusPagesService) MigrationCancel(ctx context.Context, req *CancelStatusPageMigrationRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/migration/cancel", req, nil)
}

// Get migration status.
//
// Get the current status and progress of a status page migration job.
//
// API: GET /status-page/migration/status (statusPageMigrationStatus).
func (s *StatusPagesService) MigrationStatus(ctx context.Context, req *StatusPagesMigrationStatusRequest) (*StatusPageMigrationJob, *Response, error) {
	out := new(StatusPageMigrationJob)
	resp, err := s.client.doGet(ctx, "/status-page/migration/status", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete status page section.
//
// Delete a section from a status page.
//
// API: POST /status-page/section/delete (statusPageSectionDelete).
func (s *StatusPagesService) SectionDelete(ctx context.Context, req *DeleteStatusPageSectionRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/section/delete", req, nil)
}

// Upsert status page section.
//
// Create or update a section on a status page.
//
// API: POST /status-page/section/upsert (statusPageSectionUpsert).
func (s *StatusPagesService) SectionUpsert(ctx context.Context, req *UpsertStatusPageSectionRequest) (*UpsertStatusPageSectionResponse, *Response, error) {
	out := new(UpsertStatusPageSectionResponse)
	resp, err := s.client.do(ctx, "/status-page/section/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Export subscribers.
//
// Export subscribers list for a status page as a CSV attachment. The response is a `text/csv` file with columns: Method, Recipient, Components, Subscribe All, Locale.
//
// API: POST /status-page/subscriber/export (statusPageSubscriberExport).
func (s *StatusPagesService) SubscriberExport(ctx context.Context, req *ExportStatusPageSubscribersRequest) (*StatusPageSubscriberExportResponse, *Response, error) {
	out := new(StatusPageSubscriberExportResponse)
	resp, err := s.client.do(ctx, "/status-page/subscriber/export", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Import subscribers.
//
// Bulk import subscribers for a status page.
//
// API: POST /status-page/subscriber/import (statusPageSubscriberImport).
func (s *StatusPagesService) SubscriberImport(ctx context.Context, req *ImportStatusPageSubscribersRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/subscriber/import", req, nil)
}

// List status page subscribers.
//
// List subscribers who have signed up for status page notifications.
//
// API: GET /status-page/subscriber/list (statusPageSubscriberList).
func (s *StatusPagesService) SubscriberList(ctx context.Context, req *StatusPagesSubscriberListRequest) (*StatusPageSubscriberListResponse, *Response, error) {
	out := new(StatusPageSubscriberListResponse)
	resp, err := s.client.doGet(ctx, "/status-page/subscriber/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete status page template.
//
// Delete an event template from a status page.
//
// API: POST /status-page/template/delete (statusPageTemplateDelete).
func (s *StatusPagesService) TemplateDelete(ctx context.Context, req *DeleteStatusPageTemplateRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/template/delete", req, nil)
}

// List status page templates.
//
// List all event templates for a status page.
//
// API: GET /status-page/template/list (statusPageTemplateList).
func (s *StatusPagesService) TemplateList(ctx context.Context, req *StatusPagesTemplateListRequest) (*Response, error) {
	return s.client.doGet(ctx, "/status-page/template/list", req, nil)
}

// Upsert status page template.
//
// Create or update an event template for a status page.
//
// API: POST /status-page/template/upsert (statusPageTemplateUpsert).
func (s *StatusPagesService) TemplateUpsert(ctx context.Context, req *UpsertStatusPageTemplateRequest) (*UpsertStatusPageTemplateResponse, *Response, error) {
	out := new(UpsertStatusPageTemplateResponse)
	resp, err := s.client.do(ctx, "/status-page/template/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Update status page.
//
// Update an existing status page configuration.
//
// API: POST /status-page/update (statusPageUpdate).
func (s *StatusPagesService) Update(ctx context.Context, req *UpdateStatusPageRequest) (*Response, error) {
	return s.client.do(ctx, "/status-page/update", req, nil)
}
