// Code generated by internal/cmd/gen; DO NOT EDIT.

package flashduty

import "context"

// TeamsService handles the "Platform/Teams" API resource.
type TeamsService service

// Get team detail.
//
// Return a single team by ID, name, or external reference ID.
//
// API: POST /team/info (team-read-info).
func (s *TeamsService) ReadInfo(ctx context.Context, req *TeamInfoRequest) (*TeamItem, *Response, error) {
	out := new(TeamItem)
	resp, err := s.client.do(ctx, "/team/info", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Batch get teams.
//
// Return basic info for multiple teams by their IDs in a single request.
//
// API: POST /team/infos (team-read-infos).
func (s *TeamsService) ReadInfos(ctx context.Context, req *TeamInfosRequest) (*TeamInfosResponse, *Response, error) {
	out := new(TeamInfosResponse)
	resp, err := s.client.do(ctx, "/team/infos", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// List teams.
//
// Return a paginated list of teams in the current account.
//
// API: POST /team/list (team-read-list).
func (s *TeamsService) ReadList(ctx context.Context, req *TeamListRequest) (*TeamListResponse, *Response, error) {
	out := new(TeamListResponse)
	resp, err := s.client.do(ctx, "/team/list", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}

// Delete a team.
//
// Permanently delete a team by ID, name, or external reference ID.
//
// API: POST /team/delete (team-write-delete).
func (s *TeamsService) WriteDelete(ctx context.Context, req *TeamDeleteRequest) (*Response, error) {
	return s.client.do(ctx, "/team/delete", req, nil)
}

// Create or update a team.
//
// Create a new team or update an existing one. Pass `team_id` to update.
//
// API: POST /team/upsert (team-write-upsert).
func (s *TeamsService) WriteUpsert(ctx context.Context, req *TeamUpsertRequest) (*TeamUpsertResponse, *Response, error) {
	out := new(TeamUpsertResponse)
	resp, err := s.client.do(ctx, "/team/upsert", req, out)
	if err != nil {
		return nil, resp, err
	}
	return out, resp, nil
}
